ALTAPPS-202: shared local notifications / domain
hyperskill/mobile-app pull request #109
Opened 2022-08-02 09:14 UTC by vladkash

Task: [#ALTAPPS-202](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-202)

**Dependencies**
- !

**Reviewers**
- [ ] @eqimd 

**Description**
- Добавлены cache, data, domain слои

2022-08-02 10:53 UTC, eqimd requested changes

2022-08-02 10:53 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/domain/repository/NotificationRepository.kt
> +    suspend fun getNotificationsTimestamp(): Int
Тут не хватает ключа, по которому мы будем получать уведомление. И в целом мне кажется, что логика выстроена не совсем правильно: мы должны уметь вызвать метод вроде `setNotificationTimestamp(key)`, при чем этот `key` -- это ключ, который для каждого уведомления будет свой. Например, если у нас будет запланировано уведомление на то, чтоб пользователь решил задачу дня, то у него будет ключ типа `notification_problem_of_day`, а для уведомления например на то, чтоб он прочитал какой-нибудь топик, будет ключ `notification_read_topic`, и по этим ключам мы можем получать `timestamp`, и например менять его через `set`-метод, если с ним что-то не так

2022-08-02 10:53 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheKeyValues.kt
> +    const val NOTIFICATIONS_TIMESTAMP = "notifications_timestamp"
В связи с комментарием про логику ключ `NOTIFICATION_TIMESTAMP` больше не будет нужен

2022-08-02 12:26 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/source/NotificationCacheDataSource.kt
> +    //  в теории можно обойтись Int, сохраняя просто номер часа
этот комментарий я удалю, написал чтобы ты обратил внимание и обсудить это

2022-08-02 12:29 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/source/NotificationCacheDataSource.kt
> +    //  в теории можно обойтись Int, сохраняя просто номер часа
<img width="468" alt="image" src="https://user-images.githubusercontent.com/30647936/182374494-08077b9b-c590-407f-9d73-5a5f2314c699.png">
Мне казалось, что timestamp - это вот этот временной интервал. Как раз рядом с включением уведомлений находится. Или у тебя другая инфа?

2022-08-02 12:32 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/domain/repository/NotificationRepository.kt
> +    suspend fun getNotificationsTimestamp(): Int
Я что-то не увидел в [задаче](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-202), что мы по ключу получаем уведомление. Глянешь?

2022-08-02 13:22 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/domain/repository/NotificationRepository.kt
> +    suspend fun getNotificationsTimestamp(): Int
![image](https://user-images.githubusercontent.com/28218442/182384820-a714e96d-7239-4abc-86aa-cea420d1d699.png)
По ключу мы получаем `timestamp`, а не само уведомление.
Уведомления могут быть разного характера, и если ключ будет один, то как для разных уведомлений хранить разные таймштампы?

2022-08-02 13:25 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/source/NotificationCacheDataSource.kt
> +    //  в теории можно обойтись Int, сохраняя просто номер часа
На [андроиде](https://github.com/hyperskill/mobile-app/pull/107/files) везде таймштамп -- это просто `Long`.
Время в `Schedule` это просто то время, в которое мы должны посылать напоминания о том, чтобы юзер учился. Его можно легко вычислить в таймштампах: условно будет штамп `X` для начала времени и `X + Y` для его окончания. При этом на андроиде есть система для того, чтобы уведомления перепланировались, для этого у `X` просто берется оффсет, и получаем время, на которое будет назначено новое уведомление: `X + OFFSET_24_HOURS`, например.

2022-08-02 13:25 UTC, eqimd commented
Мне кажется стоит попросить @ivan-magda , чтоб он глянул комментарии, может я и не прав

2022-08-02 13:27 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/source/NotificationCacheDataSource.kt
> +    //  в теории можно обойтись Int, сохраняя просто номер часа
Возможно на iOS по-другому система сделана?

2022-08-03 11:47 UTC, eqimd approved these changes

2022-08-03 11:53 UTC, merged

2022-08-03 14:11 UTC, ivan-magda commented
@vladkash @eqimd не понятно зачем все функции сделаны, как `suspend` функции, хотя в этом нет необходимости, т.к. весь API `com.russhwolf.settings` синхронный.

2022-08-04 08:23 UTC, vladkash commented
@ivan-magda сори, что не добавил в ревью((( казалось, что все хорошо. Каким образом теперь поступить, чтобы это поправить? Восстановить ветку и залить в нее изменения?

2022-08-04 09:39 UTC, ivan-magda commented
> @ivan-magda сори, что не добавил в ревью((( казалось, что все хорошо. Каким образом теперь поступить, чтобы это поправить? Восстановить ветку и залить в нее изменения?

@vladkash если есть активный PR с использованием этого кода, то можно прям там исправить, иначе открыть новый PR