ALTAPPS-207: shared profile settings domain
hyperskill/mobile-app pull request #112
Opened 2022-08-03 09:09 UTC by vladkash

Task: [#ALTAPPS-207](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-207)

**Dependencies**
- !

**Reviewers**
- [ ] @eqimd 

**Description**
- Добавлен domain слой для настроек профиля

2022-08-03 10:30 UTC, eqimd requested changes

2022-08-03 10:30 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/cache/ProfileSettingsCacheDataSourceImpl.kt
> +        json.decodeFromString(settings[ProfileSettingsCacheKeyValues.PROFILE_SETTINGS, ""])
Лучше использовать `.get(...)`-метод и не использовать default-значение, а выкидывать ошибку, если такого ключа в настройках нету

2022-08-03 10:30 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/cache/ProfileSettingsCacheDataSourceImpl.kt
> +    override suspend fun saveProfileSettings(profileSettings: ProfileSettings): Unit =
Этот метод не должен выглядеть так, как будто он что-то возвращает, нужно убрать `=` и обернуть в обычные скобки `{....}`

2022-08-03 10:30 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/data/repository/ProfileSettingsRepositoryImpl.kt
> +    override suspend fun saveProfileSettings(profileSettings: ProfileSettings): Unit =
Этот метод не должен выглядеть так, как будто он что-то возвращает, нужно убрать `=` и обернуть в обычные скобки `{....}`

2022-08-03 10:30 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/interactor/ProfileSettingsInteractor.kt
> +    suspend fun saveProfileSettings(profileSettings: ProfileSettings): Unit =
Этот метод не должен выглядеть так, как будто он что-то возвращает, нужно убрать `=` и обернуть в обычные скобки `{....}`

2022-08-03 10:30 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/interactor/ProfileSettingsInteractor.kt
> +class ProfileSettingsInteractor(
Мне кажется стоит добавить метод типа `changeTheme(newTheme: Theme)`, чтобы не нужно было в каждом модуле создавать новый класс, после чего сохранять его. В этом случае как раз пригодится метод `profileSettings.copy(theme = newTheme)`. Добавить его, конечно, не только в интерактор.

2022-08-03 10:38 UTC, eqimd requested changes

2022-08-03 10:38 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/ProfileSettings.kt
> +data class ProfileSettings(
Этот класс нужно обернуть в `@Serializable`, а переменные в `@SerialName(...)`, чтобы он мог быть [сериализован](https://github.com/Kotlin/kotlinx.serialization)

2022-08-03 11:27 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/cache/ProfileSettingsCacheDataSourceImpl.kt
> +        json.decodeFromString(settings[ProfileSettingsCacheKeyValues.PROFILE_SETTINGS, ""])
когда пользователь только поставит приложение у него же не будет ничего в настройках сохранено, не поломает ли ошибка приложение в таком случае?

2022-08-03 11:29 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/ProfileSettings.kt
> +data class ProfileSettings(
а enum Theme не нужно так оборачивать?

2022-08-03 11:37 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/cache/ProfileSettingsCacheDataSourceImpl.kt
> +        json.decodeFromString(settings[ProfileSettingsCacheKeyValues.PROFILE_SETTINGS, ""])
Когда пользователь поставит приложение, у него интерактор нигде не будет задействован -- он будет создан при открытии вкладки профиля.
Вообще по-хорошему в будущем нужно сделать так, чтобы при первом запуске, либо в какой-то другой хороший момент, эти настройки сохранялись, потому что как минимум у нас будет стандартное значение у поля темы (я думаю это будет `SYSTEM`)

2022-08-03 11:38 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/ProfileSettings.kt
> +data class ProfileSettings(
Я еще подумал, что в этот класс нужно добавить поля на `timestamp` и `offset`, которые будут показывать, когда пользователь поставил себе уведомления.
Например, если он поставил их на 21:00 -- 23:00, то `timestamp` будет равен миллисекундам для ближайших 21:00, а `offset` будет равен 2 часам в миллисекундах

2022-08-03 11:40 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/ProfileSettings.kt
> +data class ProfileSettings(
Хотя по-хорошему, так как у нас могут быть в будущем разные уведомления, то нужно сделать переменную `val notificationInfos: Map<String, NotificationInfo>`, который по ключу, связанному с уведомлением, будет получать `data`-класс `NotificationInfo`, в котором и будут лежать `timestamp` и `offset`

2022-08-03 11:46 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/ProfileSettings.kt
> +data class ProfileSettings(
Сори, я забыл, что у нас отдельно есть логика на уведомления в shared-модуле. Комментарии неактуальны.

2022-08-04 08:40 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/cache/ProfileSettingsCacheDataSourceImpl.kt
> +        json.decodeFromString(settings[ProfileSettingsCacheKeyValues.PROFILE_SETTINGS, ""])
Да, я про этот момент и имел ввиду. Просто сейчас реализовано так, что я в методе возвращаю default значение, но при этом если будет сохранено новое, буду возвращать него. При этом, если при обновлении приложения, скажем, у нас появятся дополнительные поля, то подход с выкидыванием ошибки плох, ведь в настройках этого нового ключа не будет. А каждый раз проверять при запуске приложения есть ли необходимые ключи кажется костылем. Давай оставим default версию в коде, как сейчас?

2022-08-04 08:44 UTC, vladkash commented
@eqimd убрал везде suspend, потому что как и при кешировании уведомлений в нем нет необходимости

2022-08-04 08:45 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/cache/ProfileSettingsCacheDataSourceImpl.kt
> +        json.decodeFromString(settings[ProfileSettingsCacheKeyValues.PROFILE_SETTINGS, ""])
В случае появления нового ключа, если его может не быть, можно сделать его nullable, например `val X: Int? = null`. Если он не может быть `null`, то тогда можно какие-нибудь стандартные значения выставлять, все равно пользователь сможет их изменить

2022-08-04 08:51 UTC, eqimd approved these changes

2022-08-04 08:51 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/cache/ProfileSettingsCacheDataSourceImpl.kt
> +        json.decodeFromString(settings[ProfileSettingsCacheKeyValues.PROFILE_SETTINGS, ""])
И тут все еще не используются `.get(...)` метод

2022-08-04 08:51 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/data/repository/ProfileSettingsRepositoryImpl.kt
> +class ProfileSettingsRepositoryImpl(
Нужно убрать `suspend` у методов этого класса

2022-08-04 08:51 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/cache/ProfileSettingsCacheDataSourceImpl.kt
> +    private fun defaultSettings(): ProfileSettings =
Название `defaultSettings` больше выглядит как переменная, чем функция, я бы назвал чем-нибудь вроде `createDefaultSettings()`

2022-08-04 08:53 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/cache/ProfileSettingsCacheDataSourceImpl.kt
> +        json.decodeFromString(settings[ProfileSettingsCacheKeyValues.PROFILE_SETTINGS, ""])
Возможно по поводу комментария выше стоит спросить @ivan-magda

2022-08-04 09:04 UTC, vladkash commented
@eqimd заисползовал get, при этом если настроек нет, возвращаю стандартное их значение

2022-08-04 13:08 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/cache/ProfileSettingsCacheDataSourceImpl.kt
> +        json.decodeFromString(settings[ProfileSettingsCacheKeyValues.PROFILE_SETTINGS, ""])
Можно было просто хранить отдельно каждую пару/ключ значение настроек, а не в рамках одной сериализуемой модели, тогда бы не было в дальнейшем проблем с миграцией данных, но `ProfileSettings` тоже ОК.

> В случае появления нового ключа, если его может не быть, можно сделать его nullable, например val X: Int? = null. Если он не может быть null, то тогда можно какие-нибудь стандартные значения выставлять, все равно пользователь сможет их изменить

лучше не делать nullable, а всегда предоставлять default value

2022-08-04 13:18 UTC, ivan-magda requested changes

2022-08-04 13:18 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/cache/ProfileSettingsCacheDataSourceImpl.kt
> +    }
Давай всегда возвращать значение без ошибки. Здесь ошибка может возникнуть в 2-х случаях: когда нет значения по ключу PROFILE_SETTINGS и при ошибке decodinga JSON.

- При отсутствии значения по ключу PROFILE_SETTINGS это нужно обработать и сохранить default значение.
- При JSON decoding error это уже ошибка программиста при разработке, делаем fatalError

2022-08-04 13:18 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/ProfileSettings.kt
> +    val theme: Theme
Здесь сразу можно указать значению по умолчанию - `SYSTEM` и в дальнейшем также лучше делать так, чтобы не было проблем при десериализации новой модели данных

2022-08-05 05:26 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/cache/ProfileSettingsCacheDataSourceImpl.kt
> +    }
пусть возвращается `Result<ProfileSettings>`, но при отсутствии значения по ключу `PROFILE_SETTINGS` это нужно обработать и сохранить default значение

2022-08-05 12:10 UTC, ivan-magda approved these changes

2022-08-06 12:09 UTC, merged