ALTAPPS-206: shared profile settings presentation
hyperskill/mobile-app pull request #114
Opened 2022-08-04 10:00 UTC by vladkash

Task: [#ALTAPPS-206](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-206)

**Reviewers**
- [ ] @ivan-magda 
- [ ] @eqimd 

**Description**
- Add profile settings presentation logic

2022-08-04 13:45 UTC, eqimd requested changes

2022-08-04 13:45 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileSettingsFeature.kt
> +    sealed interface Message {
Сюда стоит добавить месседж на то, что была изменена тема, и в recuder-е это обработать

2022-08-05 05:28 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileSettingsFeature.kt
> +    sealed interface Message {
не хватает полного MVI цикла на изменение темы

2022-08-05 09:40 UTC, vladkash commented
@ivan-magda @eqimd я добавил MVI цикл на смену темы

2022-08-05 11:05 UTC, eqimd approved these changes

2022-08-05 11:05 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileSettingsReducer.kt
> +                    State.Content(state.profileSettings.copy(theme = message.theme)) to setOf(Action.ChangeTheme(message.theme))
Мне кажется можно убрать action на изменение темы, т.к. мы все равно будем во view обрабатывать изменение состояния, а оно нам приходит уже с новой темой

2022-08-05 11:54 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileSettingsReducer.kt
> +                    State.Content(state.profileSettings.copy(theme = message.theme)) to setOf(Action.ChangeTheme(message.theme))
> Мне кажется можно убрать action на изменение темы, т.к. мы все равно будем во view обрабатывать изменение состояния, а оно нам приходит уже с новой темой

Ничего убирать не нужно, если убрать, то тогда state фичи не будет синхронизирован с view

2022-08-05 12:04 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileSettingsReducer.kt
> +                    State.Content(state.profileSettings.copy(theme = message.theme)) to setOf(Action.ChangeTheme(message.theme))
неправильно понял комментарий @eqimd, да здесь action `Action.ChangeTheme(message.theme)` лишний

2022-08-05 12:06 UTC, ivan-magda approved these changes

2022-08-05 12:06 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/Theme.kt
> +enum class Theme {
По-моему здесь тоже нужно добавить аннотацию `@Serializable`, но это не точно. Можешь это проверить написав тест на сериализацию/десереализацию или тестово заиспользовать `ProfileSettingsInteractor`, получить настроки, изменить их и проверить, что ожидание совпадает с реальностью и нет ошибок

2022-08-05 12:23 UTC, ivan-magda commented
@vladkash давай еще фичу настроек вынес в отдельный пакет `profile_settings`

2022-08-05 12:24 UTC, ivan-magda requested changes
@vladkash давай еще фичу настроек вынес в отдельный пакет `profile_settings`

2022-08-06 13:00 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/Theme.kt
> +enum class Theme {
Проверил, сериализация работает

2022-08-08 08:58 UTC, ivan-magda approved these changes

2022-08-08 09:02 UTC, merged