ALTAPPS-227: Update Cards on Home Screen After Problem Of The Day Solved
hyperskill/mobile-app pull request #119
Opened 2022-08-09 11:29 UTC by eqimd

Task: [#ALTAPPS-227](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-227)

**Reviewers**
- [ ] @ivan-magda 
- [ ] @vladkash 

**Description**
- Add SharedFlow and related logic to listen to solved problems and update home screen state when problem of the day solved
- Add ripple effect on problem of the day card (Android)
- Fix plural solve minutes in `ProblemOfDayCardFormDelegate` (Android)

2022-08-09 11:29 UTC, eqimd commented
Еще нужно поправить iOS модуль, т.к. я затрагивал `AppGraph`

2022-08-09 15:34 UTC, ivan-magda requested changes

2022-08-09 15:34 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/problem_of_day/view/delegate/ProblemOfDayCardFormDelegate.kt
> +                            state.step.secondsToComplete!!.div(60).toInt()
что-то с форматированием минут не то
<img width="422" alt="Screen Shot 2022-08-09 at 7 09 59 PM" src="https://user-images.githubusercontent.com/8586063/183687414-289cecc6-9beb-423b-909a-ae4b031ca0dc.png">

2022-08-09 15:34 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt
> +                }
Лучше это вынести в shared модуль, в `StepQuizFeature`. При получении сообщения `Message.CreateSubmissionSuccess` можно добавить проверку на `SubmissionStatus.CORRECT` и отправить action в диспатчер, где он уже кинет сообщение во flow.

2022-08-09 15:34 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt
> +            }
Для пользователя это должно выглядеть, как фоновое обновление, т.е. не нужно отображать блокирующий индикатор загрузки и в случае неудачи обновления отображать ошибку.

Давай добавим MVI цикл, который будет фоново для пользователя ходить в сеть за новыми данными и обновлять state только в случае успеха.

Также на экране профиля после решения задачи дня нужно обновлять состояние стрика.

2022-08-09 17:30 UTC, eadm reviewed
Виджет на экране профиля все ещё не будет обновлен

2022-08-09 17:30 UTC, eadm commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt
> +                }
Так как это похоже на бизнес логику, то лучше на уровне интерактора отсылать сообщение

2022-08-09 17:30 UTC, eadm commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/data/HomeRepositoryImpl.kt
> +    override val solvedProblemsSharedFlow: MutableSharedFlow<Long> =
Кажется это скорее относится к репозиторию с Submission или Step

2022-08-11 11:21 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt
> +                    .map { Message.HomeSuccess(it.firstOrNull(), problemOfDayState) }
`Message.HomeSuccess` потом отправляет `Action.LaunchTimer`, по идее flow нужно запускать только 1 раз?

2022-08-11 12:15 UTC, eadm commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/interactor/StepQuizInteractor.kt
> +    suspend fun notifyStepSolved(id: Long) {
Почему не из `createSubmission` вызывается? После `poll` с `CORRECT` статусом.

2022-08-11 12:15 UTC, eadm commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeReducer.kt
> +                    state to setOf(Action.UpdateOnProblemOfDaySolved)
Проверки на id шага не будет?

2022-08-11 12:23 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/interactor/StepQuizInteractor.kt
> +    suspend fun notifyStepSolved(id: Long) {
В `notifyStepSolved()` еще прокидывается `id` решенного шага, как его можно достать внутри функции `createSubmission()`?

2022-08-11 12:28 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeReducer.kt
> +                    state to setOf(Action.UpdateOnProblemOfDaySolved)
Не совсем понял, проверка на то, что прилетевший id совпадает с id проблемы дня в профиле? Если да, то правильно я понимаю, что это надо проверять в ActionDispatcher-е, иначе как в reducer-е получить профиль?

2022-08-11 12:31 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeReducer.kt
> +                    state to setOf(Action.UpdateOnProblemOfDaySolved)
При этом в диспатчере, внутри флоу, это сообщение выкидывается только если решена действительно задача дня

2022-08-11 14:56 UTC, eadm commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeReducer.kt
> +                    state to setOf(Action.UpdateOnProblemOfDaySolved)
`state.problemOfDayState == NeedToSolve && state.problemOfDayState.step.id == message.id`

2022-08-11 15:08 UTC, eadm commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt
> +                onNewMessage(message)
Похоже на дублирование кода с кейсом `Action.FetchHomeScreenData`

2022-08-11 15:12 UTC, eadm commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/interactor/StepQuizInteractor.kt
> +    suspend fun notifyStepSolved(id: Long) {
Можно передать в аргумент метода в `Action.CreateSubmission` есть эта информация

2022-08-12 13:05 UTC, eqimd commented
На данный момент не обновляется карточка стрика. По логам посмотрел -- проблема в том, что из API приходит необновленная информация. Буду разбираться, проблема на стороне бэка, или в приложении. Скорее всего на стороне бэка, потому что состояние задачи дня приходит и обновляется правильно, и со стриком не должно быть никаких проблем. Сейчас к сожалению не могу, т.к. у меня закончились аккаунты с нерешенной проблемой дня.

2022-08-12 15:27 UTC, eadm approved these changes

2022-08-15 11:04 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt
> +                    .getOrThrow()
`.getOrElse { return }`

2022-08-15 11:05 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt
> +                    .getOrThrow()
и выше тоже

2022-08-15 11:07 UTC, ivan-magda approved these changes

2022-08-15 11:17 UTC, merged