ALTAPPS-222: Android Schedule Daily Reminder Notification
hyperskill/mobile-app pull request #121
Opened 2022-08-11 11:41 UTC by eqimd

Task: [#ALTAPPS-222](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-222)

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Add UI for scheduling daily notifications from profile fragment
- Add daily reminder notification delegate

2022-08-11 11:41 UTC, eqimd commented
Уведомления приходят в назначенный час + 7.5 минут (15 минут пополам)

2022-08-15 15:33 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/DailyStudyReminderNotificationDelegate.kt
> +        if (!notificationInteractor.isNotificationsEnabled()) {
`notificationInteractor.isNotificationsEnabled()` по названию может сложиться впечатление о том, что флаг отвечает за то, что включены/выключены у пользователя в принципе локальные уведомления, хотя это не так.

В старых и актуальных макетах настроек приложения нет такой возможности для включения/выключения локальных уведомлений.

Давай переименуем в `NotificationInteractor -> NotificationRepository -> NotificationCacheDataSource`:
- `fun isNotificationsEnabled(): Boolean` -> `fun isDailyStudyRemindersEnabled(): Boolean`
- `fun setNotificationsEnabled(enabled: Boolean)` -> `fun setDailyStudyRemindersEnabled(enabled: Boolean)`

и в `NotificationCacheKeyValues`:
- `NOTIFICATIONS_ENABLED` -> `NOTIFICATIONS_DAILY_REMINDER_ENABLED`

2022-08-15 15:36 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt
>          // TODO
TODO можно удалить?

2022-08-15 15:48 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheDataSourceImpl.kt
>      private fun getNotificationDescriptions() =
`getDailyStudyRemindersNotificationDescriptions `

2022-08-15 15:48 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheDataSourceImpl.kt
> +    override fun getRandomNotificationDescription(): NotificationDescription =
`getRandomDailyStudyRemindersNotificationDescription `

2022-08-15 15:54 UTC, ivan-magda requested changes
OK, каждый день уведомления приходят в выбранный час со случайным текстом. Давай пофиксим именование daily study уведомлений из моих комментариев выше и на этом все.

2022-08-16 09:21 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheKeyValues.kt
> +    const val NOTIFICATIONS_DAILY_REMINDER_ENABLED = "notifications_enabled"
```suggestion
    const val NOTIFICATIONS_DAILY_REMINDER_ENABLED = "notifications_daily_reminder_enabled"
```

2022-08-16 09:22 UTC, ivan-magda approved these changes

2022-08-16 10:24 UTC, merged