ALTAPPS-225: iOS onboarding screen
hyperskill/mobile-app pull request #123
Opened 2022-08-11 14:48 UTC by vladkash

Task: [#ALTAPPS-225](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-225)

**Dependencies**
- !

**Reviewers**
- [ ] @ivan-magda 
- [ ] @eqimd 

**Description**
- Added caching isOnboardingShowed key

2022-08-15 16:31 UTC, ivan-magda commented
> @ivan-magda я только не могу понять, почему при выходе из профиля не показывается fullScreenCover

@vladkash я думаю это из-за того, что при выходе из профиля практически в одно и то же время происходят значительные изменения в иерархии SwiftUI state, обновление AppFeature state и ViewAction изменяющий AppNavigationState конфликтуют. Возможно fullScreenCover при ViewAction изменяющий AppNavigationState еще связан с TabView, а не с ProgressView.

Если в `handleViewAction(_ viewAction: AppFeatureActionViewAction)` добавить задержку, то проблема исчезает:
```swift
private func handleViewAction(_ viewAction: AppFeatureActionViewAction) {
    DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
        switch viewAction {
        case is AppFeatureActionViewActionNavigateToOnboardingScreen:
            withAnimation {
                viewModel.navigationState.presentingScreen = .onboarding
            }
....
```

подумаю как лучше сделать.

2022-08-15 20:37 UTC, ivan-magda requested changes

2022-08-15 20:37 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift
> +    enum Onboarding {
new line before

2022-08-15 20:37 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppPresentingScreen.swift
> +enum AppPresentingScreen: Identifiable {
`AppFullScreenModal`

2022-08-15 20:37 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppNavigationState.swift
> +    var presentingScreen: AppPresentingScreen?
`var activeFullScreenModal: AppFullScreenModal?`

2022-08-15 20:37 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppView.swift
> +            .fullScreenCover(item: $viewModel.navigationState.presentingScreen) { screen in
👍

2022-08-15 20:37 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppViewModel.swift
> +    func openAuthScreen() {
`func doAuthPresentation()`

2022-08-15 20:37 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppViewModel.swift
> +    func openNewUserScreen() {
`func doNewUserPresentation()`

2022-08-15 20:37 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Onboarding/OnboardingView.swift
> +                .ignoresSafeArea()
`Color(ColorPalette.background).ignoresSafeArea()` -> `BackgroundView()`

2022-08-15 20:37 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Onboarding/OnboardingView.swift
> +                    .font(.title)
`.font(.largeTitle)`

2022-08-15 20:37 UTC, ivan-magda commented on shared/src/commonMain/resources/MR/base/strings.xml
> +    <string name="onboarding_title">Welcome to Hyperskill</string>
```suggestion
    <string name="onboarding_title">Welcome\nto Hyperskill</string>
```

2022-08-15 20:37 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Onboarding/OnboardingView.swift
> +
лишний перенос строки

2022-08-16 08:42 UTC, eqimd commented on shared/src/commonMain/resources/MR/base/strings.xml
> +    <string name="onboarding_card_text">Practice what you've learned</string>
и апострофы надо экранировать через `\'`

2022-08-16 08:44 UTC, eqimd approved these changes
Аппрувнул по модулю замечаний Вани

2022-08-16 12:35 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/injection/AndroidAppComponentImpl.kt
> +
```
/**
 * Onboarding component
 */
```

2022-08-16 12:43 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Onboarding/OnboardingAssembly.swift
> +    private let onSignUpTap: () -> Void
Нужно заменить на OutputProtocol (реализуется вьюмоделью другого модуля, позволяет модулю взаимодействовать с окружающим миром). Для примера можешь посмотреть на существующие модули.

`OnboardingView Sign in button tapped` -> `OnboardingView.viewModel.doSignInPresentation()` -> `OnboardingViewModel.moduleOutput.handleOnboardingSignInRequested()`

2022-08-16 12:47 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Onboarding/OnboardingViewModel.swift
> +OnboardingFeatureActionViewAction
2 пробела
<img width="499" alt="Screen Shot 2022-08-16 at 4 46 41 PM" src="https://user-images.githubusercontent.com/8586063/184883025-ac9935de-880f-461c-bec9-d8598ef3cb9d.png">

2022-08-16 12:49 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/onboarding/cache/OnboardingCacheDataSourceImpl.kt
> +    override fun setOnboardingShown(showed: Boolean) {
`override fun setOnboardingShown(isShown: Boolean)`

2022-08-16 12:50 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/onboarding/data/repository/OnboardingRepositoryImpl.kt
> +    override fun setOnboardingShown(showed: Boolean) {
`override fun setOnboardingShown(isShown: Boolean)`

2022-08-16 12:50 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/onboarding/data/source/OnboardingCacheDataSource.kt
> +    fun setOnboardingShown(showed: Boolean)
`fun setOnboardingShown(isShown: Boolean)`

2022-08-16 12:53 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/onboarding/domain/interactor/OnboardingInteractor.kt
> +    fun setOnboardingShown(showed: Boolean) {
`fun setOnboardingShown(isShown: Boolean)`

2022-08-16 12:53 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/onboarding/domain/repository/OnboardingRepository.kt
> +    fun setOnboardingShown(showed: Boolean)
`fun setOnboardingShown(isShown: Boolean)`

2022-08-16 12:59 UTC, ivan-magda requested changes
@vladkash нужно подмерджить `develop`

2022-08-16 14:03 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Onboarding/OnboardingOutputProtocol.swift
> +    func doNewUserPresentation()
```swift
func handleOnboardingSignInRequested()

func handleOnboardingSignUnRequested()
```

2022-08-16 14:13 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/onboarding/injection/OnboardingComponentImpl.kt
> +        get() = OnboardingInteractor(onboardingRepository)
```kotlin
override val onboardingInteractor: OnboardingInteractor =
    OnboardingInteractor(onboardingRepository)
```

2022-08-16 14:19 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/onboarding/injection/OnboardingComponentImpl.kt
> +        get() = OnboardingInteractor(onboardingRepository)
@vladkash OK, не нужно изменять

2022-08-16 14:57 UTC, ivan-magda approved these changes
я посмотрю на багу при выходе из профиля и после смерджим

2022-08-16 15:41 UTC, ivan-magda commented
@vladkash SwiftUI, так же, как и UIKit, работает поверх render loop’а. В большинстве случаев нам об этом практически ничего не надо знать, но иногда понимание его устройства полезно. Вот отличная статья с разбором https://rensbr.eu/blog/swiftui-render-loop/.

До этого у нас в `FeatureViewModel` обновление `State` и уведомление об `ViewAction` могло произойти одновременно, как при выходе из профиля и из-за этого SwiftUI рендерил состояние не так, как мы ожидали.
В aaed2c37456810c411166753af2d2862a06c36df я уведомления об `ViewAction` отложил до следующего render loop’а и это помогло.

Можно мерджить.

2022-08-17 06:03 UTC, merged