ALTAPPS-235: shared real notifications texts
hyperskill/mobile-app pull request #124
Opened 2022-08-12 08:16 UTC by vladkash

Task: [#ALTAPPS-235](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-235)

**Reviewers**
- [ ] @eqimd 
- [ ] @ivan-magda 

**Description**
- Added real texts of notifications to shared module

2022-08-12 08:59 UTC, eqimd requested changes

2022-08-12 08:59 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheDataSourceImpl.kt
> +        return notifications.shuffled().first()
лучше `notifications.random()`

2022-08-12 08:59 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheDataSourceImpl.kt
> +        val notifications = listOf(
мне кажется их стоит вынести в отдельную функцию и назвать как-нибудь вроде `getNotificationDescriptions()`

2022-08-12 08:59 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheDataSourceImpl.kt
> +        val notifications = listOf(
и из этой функции просто возвращать `getNotificationDescriptions().random()`

2022-08-12 08:59 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/model/Notification.kt
> +data class Notification(
слишком "обширное" название, давай назовем просто `NotificationDescription`

2022-08-12 08:59 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/model/Notification.kt
> +    val desc: String
`desc` давай переименуем в `text`

2022-08-12 09:13 UTC, eqimd approved these changes

2022-08-12 09:13 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheDataSourceImpl.kt
> +    private fun getNotificationDescriptions() =
можно и не приватной, вдруг где-то нужно будет еще использовать

2022-08-12 09:16 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheDataSourceImpl.kt
> +    private fun getNotificationDescriptions() =
ну когда надо, тогда откроем, а пока давай последуем принципу максимальной закрытости)

2022-08-12 09:16 UTC, merged

2022-08-12 09:16 UTC, vladkash commented
@ivan-magda как сможешь посмотри, пожалуйста, не натворили ли мы чего

2022-08-15 11:23 UTC, ivan-magda commented
> @ivan-magda как сможешь посмотри, пожалуйста, не натворили ли мы чего

@vladkash OK, в дальнейшем лучше именовать все что связано с определёнными уведомлениями более конкретно, т.к. число уведомлений будет расти...

- `fun getRandomNotification(): NotificationDescription` -> `fun getRandomDailyNotification(): NotificationDescription`
- `notification1_title` -> `daily_notification1_title`
- `notification1_text` -> `daily_notification1_text`