ALTAPPS-230: iOS notifications settings & scheduling
hyperskill/mobile-app pull request #125
Opened 2022-08-15 10:40 UTC by vladkash

Task: [#ALTAPPS-](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-)

**Dependencies**
- !

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Added notifications settings saving & notifications scheduling

2022-08-15 10:42 UTC, vladkash commented
@ivan-magda я не совсем понял, каким образом должно планироваться следующее уведомление, после первого, чтобы оно было с новым текстом и на следующую дату, подскажи этот момент, пожалуйста? Также хотел спросить, при сохранении нового времени уведомления старые уведомления отменять нужно получается?

2022-08-16 08:11 UTC, ivan-magda commented
@vladkash 

> @ivan-magda я не совсем понял, каким образом должно планироваться следующее уведомление, после первого, чтобы оно было с новым текстом и на следующую дату, подскажи этот момент, пожалуйста? 

Короткий ответ ни как, но можно сделать нечто похожее:
У нас имеется список с текстами для 12 уведомлений. Можно сразу запланировать все эти уведомления пачкой, один за другим и тогда на протяжении следующих 12 дней мы добьёмся возникновения случайных уведомлений. При планировании этот список лучше перемешивать. Также в момент, когда приложение стало активно [applicationDidBecomeActive(_:)](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622956-applicationdidbecomeactive) нужно их перепланировать.

> Также хотел спросить, при сохранении нового времени уведомления старые уведомления отменять нужно получается?

Да, нужно. Можно из Stepik перенести `NotificationsService`, где есть расширение для локальных уведомлений https://github.com/StepicOrg/stepik-ios/blob/master/Stepic/Sources/Frameworks/Notifications/NotificationsService.swift#L74-L95

2022-08-16 08:21 UTC, ivan-magda requested changes

2022-08-16 08:21 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/Local/ConcreteNotifications/ReminderLocalNotification.swift
> +struct ReminderLocalNotification: LocalNotificationProtocol {
`DailyStudyReminderLocalNotification`

2022-08-16 08:21 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/ProfileViewModel.swift
> +    func isRemindersActivated() -> Bool {
`isDailyStudyRemindersEnabled`

2022-08-16 08:21 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/ProfileViewModel.swift
> +    func setRemindersActivated(activated: Bool) async {
`setDailyStudyRemindersActivated(_ isActivated:)`

2022-08-16 08:21 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/ProfileViewModel.swift
> +        await self.scheduleNotification()
Зачем уведомления планируются при `activated == false`?

2022-08-16 08:21 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/ProfileViewModel.swift
> +    func getRemindersSelectedHour() -> Int {
`getDailyStudyRemindersStartHour`

2022-08-16 08:21 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/ProfileViewModel.swift
> +    func setRemindersSelectedHour(selectedHour: Int) async {
`setDailyStudyRemindersStartHour(selectedHour:)`

2022-08-16 08:21 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/ProfileViewModel.swift
> +    }
Вынести в `NotificationsService`, для примера https://github.com/StepicOrg/stepik-ios/blob/master/Stepic/Sources/Frameworks/Notifications/Local/ConcreteNotifications/StreakLocalNotification.swift#L54-L66

2022-08-18 09:49 UTC, vladkash commented
@ivan-magda мне кажется, напрашивается добавить NotificationInteractor в NotificationService и сделать функции планирования и уведомления напоминаний без аргументов за счет этого. Проверку на то, что включены уведомления тоже вынести в NotificationService, чтобы в AppDelegate был максимально простой вызов, вызовы в ProfileViewModel тоже упростятся

2022-08-18 10:31 UTC, ivan-magda commented
> @ivan-magda мне кажется, напрашивается добавить NotificationInteractor в NotificationService и сделать функции планирования и уведомления напоминаний без аргументов за счет этого. Проверку на то, что включены уведомления тоже вынести в NotificationService, чтобы в AppDelegate был максимально простой вызов, вызовы в ProfileViewModel тоже упростятся

да, я тебе об этом писал в комментарии https://github.com/hyperskill/mobile-app/pull/125#discussion_r946474775

2022-08-18 10:41 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/AppDelegate.swift
> +        }
Инкапсулировать все это в одном вызове:
```swift
notificationsService.scheduleDailyStudyRemindersLocalNotifications()
```

2022-08-18 10:44 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/Local/ConcreteNotifications/DailyStudyReminderLocalNotification.swift
> +        notificationDescritpion: NotificationDescription,
опечатка `notificationDescription`

2022-08-18 10:48 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/Local/ConcreteNotifications/DailyStudyReminderLocalNotification.swift
> +            self.trigger = UNCalendarNotificationTrigger(dateMatching: dateComponents, repeats: true)
`repeats: false`

2022-08-18 11:15 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/Local/ConcreteNotifications/DailyStudyReminderLocalNotification.swift
> +        )
При изменении числа уведомлений в shared модуле может возникнуть ситуация, когда локальное уведомление не будет отменено. Лучше сразу отменить все.

В `LocalNotificationsService` добавить возможно удаления по условию:
```swift
func removeNotifications(matching condition: (String) -> Bool) async {
    let (pending, delivered) = await getAllNotifications()

    let filteredPending = pending.filter({ condition($0.identifier) })
    if !filteredPending.isEmpty {
        removePendingNotificationRequests(identifiers: filteredPending.map(\.identifier))
    }

    let filteredDelivered = delivered.filter({ condition($0.request.identifier) })
    if !filteredDelivered.isEmpty {
        removeDeliveredNotifications(identifiers: filteredDelivered.map(\.request.identifier))
    }
}
```

в `NotificationsService` добавить
```swift
func removeLocalNotifications(matching condition: (String) -> Bool) async {
    await self.localNotificationsService.removeNotifications(matching: condition)
}
```

и далее здесь вызов будет выглядеть примерно так
```swift
Task {
    self.removeLocalNotifications { identifier in
        identifier.starts(with: DailyStudyReminderLocalNotification.identifierPrefix)
    }
}
```

2022-08-18 11:17 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/NotificationsService.swift
> +    }
можно удалить

2022-08-18 11:47 UTC, ivan-magda requested changes
@vladkash я тут подумал, давай лучше будем планировать первые случайные 7 нотификаций, в каждый день день недели (пн, вт, ср...) и которые будут повторяться (`repeats: true`).
https://stackoverflow.com/questions/41330358/repeat-usernotification-every-specific-day-of-week-for-ios-10

2022-08-18 15:32 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/AppDelegate.swift
> +    }
Перенести этот кусок кода после `application(_:didFinishLaunchingWithOptions:)` и добавить разделитель `// MARK: Responding to App Life-Cycle Events`

2022-08-18 15:33 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/Local/ConcreteNotifications/DailyStudyReminderLocalNotification.swift
> +    var identifier: String { "\(notificationNumber)" }
```suggestion
    var identifier: String { "\(Self.identifierPrefix)-\(notificationNumber)" }
```

2022-08-18 15:38 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/Local/ConcreteNotifications/DailyStudyReminderLocalNotification.swift
> +        if self.notificationInteractor.isDailyStudyRemindersEnabled() {
`guard` поможет избежать вложенности

2022-08-18 15:41 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/NotificationsService.swift
> +    let notificationInteractor: NotificationInteractor =
должен быть приватным и инициализироваться в конструкторе:
`private let notificationInteractor: NotificationInteractor`

2022-08-18 15:47 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/ProfileViewModel.swift
> +    }
Это можно вынести в `ProfileViewData`

2022-08-18 15:52 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/ProfileViewModel.swift
> +        notificationService.scheduleDailyStudyReminderLocalNotifications()
`if isActivated do smt else do other`

2022-08-18 15:54 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/ProfileDailyStudyRemindersView.swift
> +    private var setActivated: (Bool) -> Void
`onIsActivatedChanged`

2022-08-18 15:55 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/ProfileDailyStudyRemindersView.swift
> +    private var setSelectedHour: (Int) -> Void
`onSelectedHourChanged`

2022-08-18 15:58 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheDataSourceImpl.kt
> +        getDailyStudyRemindersNotificationDescriptions().shuffled().take(DAILY_STUDY_REMINDERS_COUNT)
Давай `.take(DAILY_STUDY_REMINDERS_COUNT)` вынесем в iOS https://developer.apple.com/documentation/swift/array/prefix(_:)

2022-08-18 16:02 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/Local/ConcreteNotifications/DailyStudyReminderLocalNotification.swift
> +                    await self.scheduleLocalNotification(notification)
`self.scheduleLocalNotification(notification, removeIdentical: false)` и в начале функции я бы всегда вызывал `await self.internalRemoveDailyStudyReminderLocalNotifications()`

2022-08-19 06:53 UTC, vladkash commented on iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/NotificationsService.swift
> +    let notificationInteractor: NotificationInteractor =
Перенес инициализацию в конструктор, приватным сделать мешает то, что поле используется в расширениях, расположенных в других файлах (DailyStudyReminderLocalNotification). Кажется, что добавлять getter к поле, которое не изменяется излишне

2022-08-19 11:35 UTC, ivan-magda requested changes

2022-08-19 11:35 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/Local/ConcreteNotifications/DailyStudyReminderLocalNotification.swift
> +                    startHour: Int(self.notificationInteractor.getDailyStudyRemindersIntervalStartHour()),
У меня приложение крашится при попытке обратиться к `notificationInteractor`:
```text
Uncaught Kotlin exception: kotlin.native.IncorrectDereferenceException: illegal attempt to access non-shared org.hyperskill.app.notification.domain.NotificationInteractor@38bb788 from other thread
    at 0   shared                              0x0000000111742d11 kfun:kotlin.Throwable#<init>(kotlin.String?){} + 97 (/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Throwable.kt:24:56)
    at 1   shared                              0x000000011173c05d kfun:kotlin.Exception#<init>(kotlin.String?){} + 93 (/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:23:58)
    at 2   shared                              0x000000011173c27d kfun:kotlin.RuntimeException#<init>(kotlin.String?){} + 93 (/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:34:58)
    at 3   shared                              0x0000000111773f3d kfun:kotlin.native.IncorrectDereferenceException#<init>(kotlin.String){} + 93 (/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/Runtime.kt:34:50)
    at 4   shared                              0x00000001117779ef ThrowIllegalObjectSharingException + 623 (/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/concurrent/Internal.kt:115:11)
    at 5   shared                              0x0000000111975f32 _ZN12_GLOBAL__N_128throwIllegalSharingExceptionEP9ObjHeader + 34
    at 6   shared                              0x000000011197744d _ZN12_GLOBAL__N_136terminateWithIllegalSharingExceptionEP9ObjHeader + 13
    at 7   shared                              0x00000001119775c9 _ZNK27BackRefFromAssociatedObject3refIL11ErrorPolicy3EEEP9ObjHeaderv + 185
    at 8   shared                              0x00000001117257d5 -[KotlinBase toKotlin:] + 21
    at 9   shared                              0x000000011196717e Kotlin_ObjCExport_refFromObjC + 78
    at 10  shared                              0x00000001116a92ef objc2kotlin.4440 + 143 (/<compiler-generated>:1:0)
    at 11  iosHyperskillApp                    0x000000010abb6d90 $s16iosHyperskillApp20NotificationsServiceC031scheduleDailyStudyReminderLocalD0yyFyyYaYbcfU_TQ0_ + 272 (/Users/jetbrains/Developer/hyperskill/mobile-app/iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/Local/ConcreteNotifications/DailyStudyReminderLocalNotification.swift:66:18)
    at 12  libswift_Concurrency.dylib          0x000000010ee04426 _ZN5swift34runJobInEstablishedExecutorContextEPNS_3JobE + 70
    at 13  libswift_Concurrency.dylib          0x000000010ee04d2d _ZL17swift_job_runImplPN5swift3JobENS_11ExecutorRefE + 77
    at 14  libdispatch.dylib                   0x000000010f17c160 _dispatch_continuation_pop + 93
    at 15  libdispatch.dylib                   0x000000010f17b739 _dispatch_async_redirect_invoke + 771
    at 16  libdispatch.dylib                   0x000000010f18bba2 _dispatch_root_queue_drain + 419
    at 17  libdispatch.dylib                   0x000000010f18c64e _dispatch_worker_thread2 + 196
    at 18  libsystem_pthread.dylib             0x000000010fd72f8a _pthread_wqthread + 256
    at 19  libsystem_pthread.dylib             0x000000010fd71f57 start_wqthread + 15
```

Насколько я понял нельзя перемещать Kotlin объекты между разными потоками, т.к. может возникнуть утечка памяти https://stackoverflow.com/a/58763423/5929139. У нас `notificationInteractor` создан на главном потоке, а обращаемся мы к нему из фонового.

Нужно вынести обращения к `notificationInteractor` из `Task { ... }` и NotificationDescription заменить на value type.

`func scheduleDailyStudyReminderLocalNotifications` будет выглядеть примерно так
```swift
func scheduleDailyStudyReminderLocalNotifications() {
    guard self.notificationInteractor.isDailyStudyRemindersEnabled() else {
        return
    }

    self.removeDailyStudyReminderLocalNotifications()

    let notificationDescriptions = self.notificationInteractor
        .getShuffledDailyStudyRemindersNotificationDescriptions()
        .prefix(Self.dailyStudyRemindersCount)
        .map(NotificationDescriptionPlainObject.init(notificationDescription:))

    assert(notificationDescriptions.count == Self.dailyStudyRemindersCount)

    let startHour = Int(self.notificationInteractor.getDailyStudyRemindersIntervalStartHour())

    Task {
        await self.removeDailyStudyReminderLocalNotifications()

        for (index, notificationDescription) in notificationDescriptions.enumerated() {
            let notification = DailyStudyReminderLocalNotification(
                notificationDescription: notificationDescription,
                startHour: startHour,
                notificationNumber: index + 1
            )
            await self.scheduleLocalNotification(notification, removeIdentical: false)
        }
    }
}
```

и `NotificationDescriptionPlainObject`:
```swift
struct NotificationDescriptionPlainObject {
    let title: String
    let text: String
}

extension NotificationDescriptionPlainObject {
    init(notificationDescription: NotificationDescription) {
        self.title = notificationDescription.title
        self.text = notificationDescription.text
    }
}
```

2022-08-19 13:08 UTC, vladkash commented on iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/Local/ConcreteNotifications/DailyStudyReminderLocalNotification.swift
> +                    startHour: Int(self.notificationInteractor.getDailyStudyRemindersIntervalStartHour()),
очень много нового узнал, спасибо за подробные комментарии!

2022-08-19 14:04 UTC, ivan-magda approved these changes
@vladkash можно мерджить 🚀

2022-08-19 14:18 UTC, merged