ALTAPPS-240: iOS problem of day card opening fix
hyperskill/mobile-app pull request #126
Opened 2022-08-15 12:37 UTC by vladkash

Task: [#ALTAPPS-240](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-240)

**Dependencies**
- !

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Fixed opening problem of day
-

2022-08-15 12:39 UTC, vladkash commented
@ivan-magda я обратил внимание, что из shared модуля мы получаем полноценный step, при этом StepAssembly сейчас параметризуется идентитфикатором шага, то есть он подгружается еще раз. Если на андроиде тоже используется только идентификатор шага, предлагаю оставить только его в shared модуле, в противном случае предлагаю на iOS не подгружать step, а брать его готовый из состояния Homscreen.

2022-08-15 12:39 UTC, vladkash commented
@eqimd на андроиде используется в состоянии Homescreen только step.id или там полноценно используется весь step?

2022-08-15 13:43 UTC, vladkash commented
Выяснилось, что на андроиде тоже используется только идентификатор степа, поэтому предлагаю в shared модуле в ProblemOfDayState.NeedToSolve и ProblemOfDayState.Solved хранить только stepID: Int, благодаря этому подгрузка будет происходить только один раз на обеих платформах. Сейчас подгружается два раза - в shared модуле и на платформе

2022-08-16 07:25 UTC, ivan-magda commented
> @ivan-magda я обратил внимание, что из shared модуля мы получаем полноценный step, при этом StepAssembly сейчас параметризуется идентитфикатором шага, то есть он подгружается еще раз. Если на андроиде тоже используется только идентификатор шага, предлагаю оставить только его в shared модуле, в противном случае предлагаю на iOS не подгружать step, а брать его готовый из состояния Homscreen.

@vladkash Assembly – точка сборки модуля. Модули должны инициализироваться идентификаторами, а не моделями. Interactor – содержит основную бизнес-логику модуля: отвечает за получение различных данных из нескольких источников, из сети или из персистентного хранилища.

2022-08-16 07:32 UTC, ivan-magda requested changes
При нажатии на карточку ничего не происходит, нажатие обрабатывается только для кнопки в правом верхнем углу. Вся область карточки задачи дня должна быть кликабельной.

2022-08-16 07:32 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProblemOfDay/ViewData/ProblemOfDayViewDataMapper.swift
> +            let stepID = solvedStateOrNil?.step.id ?? needToSolveStateOrNil?.step.id
`guard let`

2022-08-16 09:13 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProblemOfDay/Views/ProblemOfDayCardView.swift
> +                    EmptyView()
возвращать `EmptyView` не обязательно, т.к. это `@ViewBuilder`

2022-08-16 09:14 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProblemOfDay/Views/ProblemOfDayCardView.swift
> +                            : appearance.titleIconSizeDefault
форматирование съехало
<img width="363" alt="Screen Shot 2022-08-16 at 1 13 42 PM" src="https://user-images.githubusercontent.com/8586063/184843485-f026b49f-93fc-4c69-b39f-d90733c796ad.png">

2022-08-16 09:16 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProblemOfDay/Views/ProblemOfDayTitle.swift
>      let isArrowDisabled: Bool
`isArrowDisabled` не используется, можно удалить

2022-08-16 12:18 UTC, vladkash commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProblemOfDay/Views/ProblemOfDayCardView.swift
> +                            : appearance.titleIconSizeDefault
даже если я нажимаю ctrl+i оно не форматирует как надо, можно добиться этого эффекта через автокоррекцию линтера или форматирование xcode?

2022-08-16 12:22 UTC, ivan-magda approved these changes

2022-08-16 12:50 UTC, merged