ALTAPPS-245: Add functional to ask user to enable daily reminders after problem of day solved
hyperskill/mobile-app pull request #137
Opened 2022-08-23 09:14 UTC by eqimd

Task: [#ALTAPPS-245](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-245)

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Add functional to ask user to enable daily reminders after problem of day solved

2022-08-23 14:42 UTC, ivan-magda requested changes

2022-08-23 14:42 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/extension/AppConstants.kt
> +object AppConstants {
а мы точно хотим выносить эти константы на уровень приложения, может лучше на уровне пакета `org.hyperskill.app.notification`, т.к. они связаны только с нотификациями ?

2022-08-23 14:42 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/domain/NotificationInteractor.kt
> +        if (submissionRepository.getStepsInAppSolved() == 0L) {
здесь по идее должна быть проверка `submissionRepository.getStepsInAppSolved() <= 1L`, т.к. в `SubmissionRepositoryImpl.notifyStepSolved(id:)` сначала инкрементируется число решённых шагов и только потом отправляется `stepId` во flow

2022-08-23 14:42 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/cache/SubmissionCacheKeyValues.kt
> +    const val STEPS_SOLVED_IN_APP = "steps_solved_in_app_key"
`const val STEPS_SOLVED_COUNT = "steps_solved_count_key"`

2022-08-23 14:42 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/data/source/SubmissionCacheDataSource.kt
> +    fun getStepsInAppSolved(): Long
`getSolvedStepsCount`

2022-08-23 14:42 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/data/source/SubmissionCacheDataSource.kt
> +    fun incrementStepsInAppSolved()
`incrementSolvedStepsCount`

2022-08-23 14:42 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/repository/SubmissionRepository.kt
> +    suspend fun notifyStepSolved(id: Long)
`suspend fun notifyStepSolved(stepId: Long)`

2022-08-23 14:42 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizActionDispatcher.kt
> +                notificationInteractor.setDailyStudyRemindersIntervalStartHour(AppConstants.DAILY_REMINDERS_AFTER_STEP_SOLVED_START_HOUR)
можно добавить функцию `notificationInteractor.setDefaultDailyStudyRemindersIntervalStartHour()` и тогда не прийдется константу `AppConstants.DAILY_REMINDERS_AFTER_STEP_SOLVED_START_HOUR` делать публичной на все приложение

2022-08-23 14:42 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/cache/SubmissionCacheKeyValues.kt
> +    const val STEPS_SOLVED_IN_APP = "steps_solved_in_app_key"
при разлогине нужно очищать

2022-08-24 08:55 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/domain/NotificationInteractor.kt
> +        }
> По умолчанию isDailyStudyRemindersEnabled() == false, тогда ветка логики после первого завершения шага не отработает

Так тогда этот `if` будет пропущен, и будет проверка на то, что пока что решено 0 шагов, и вернется `true`

> Также может быть не первое завершение шага и у пользователя не включены нотификации

Тогда дальше будет проверка, когда последний раз спрашивалось про включение уведомлений, и т.д.

> Также пользователь может до первого завершения шага перейти на вкладку профиля, включить daily reminders, а потом передумать и выключить их

В таком случае проверка на `isDailyStudyRemindersEnabled()` скипнется, проверка на `getSolvedStepsCount() == 0` тоже скипнется, но вот эта строчка
```
 val lastTimeAsked = notificationRepository.getLastTimeUserAskedToEnableDailyReminders() ?: return true
```
вернет `true`

2022-08-24 08:55 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/domain/NotificationInteractor.kt
> +        }
Возможно я не совсем правильно понял замечания -- можешь уточнить?

2022-08-24 09:00 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizActionDispatcher.kt
> +                notificationInteractor.setDailyStudyRemindersIntervalStartHour(AppConstants.DAILY_REMINDERS_AFTER_STEP_SOLVED_START_HOUR)
Мне кажется тогда может возникнуть путанница -- дефолтное значение, если пользователь включает уведомления через вкладку профиля, это 20. А дефолтное значение в данном случае -- 12. Стоит ли в таком случае все равно делать такую функцию?

2022-08-24 09:01 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/domain/NotificationInteractor.kt
> +        }
@eqimd моя ошибка, я не знаю почему-то сломался на условии `notificationRepository.isDailyStudyRemindersEnabled()` 😅 Ты выше все правильно написал 👍

2022-08-24 10:45 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheDataSourceImpl.kt
> +        settings.remove(NotificationCacheKeyValues.NOTIFICATION_LAST_TIME_USER_ASKED_TO_ENABLE_DAILY_REMINDERS)
Уточню у Даши с точки зрения продукта нужно ли такую информацию очищать

2022-08-25 21:15 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheDataSourceImpl.kt
> +        settings.remove(NotificationCacheKeyValues.NOTIFICATION_LAST_TIME_USER_ASKED_TO_ENABLE_DAILY_REMINDERS)
@eqimd при разлогине ничего очищать не будем, можешь просто сделать реверт коммита 57ffce41d2c2e8cdebd4a2be1c4f23d2c3012e62 и давай мерджить.

2022-08-25 21:15 UTC, ivan-magda approved these changes

2022-08-26 07:51 UTC, merged