ALTAPPS-248: iOS improve problem of day states
hyperskill/mobile-app pull request #142
Opened 2022-08-24 08:07 UTC by vladkash

Task: [#ALTAPPS-](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-)

**Dependencies**
- !

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Fixed step quiz continue button
- Added home screen keep learning in web button

2022-08-24 14:47 UTC, ivan-magda requested changes
Мне пока что не нравится как реализована логика отображения кнопки _Continue_ и дальнейшее навигирование на Home screen по нажатию на нее. Дам комментарий о том как лучше сделать после мерджа аналогичного PR для Android #144.

2022-08-24 14:47 UTC, ivan-magda commented on shared/src/commonMain/resources/MR/base/strings.xml
> +    <string name="home_keep_learning_button_text">Keep learning in web</string>
Можно удалить. Текст должен быть `Continue learning on the web` и у нас уже есть такой строковый ресурс `track_continue_in_web_text`.

2022-08-24 14:47 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/Views/HomeView.swift
> +                    if data.problemOfDayState as? HomeFeatureProblemOfDayStateNeedToSolve == nil {
Не очень очевидное условие, было бы лучше явно проверить, что задача дня находится в пустом или решённом состоянии.

> Кнопку _Continue learning on the web_ нужно отображать если задача дня решена или ее нет

2022-08-24 14:47 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/Views/HomeView.swift
> +                            url: HyperskillURLFactory.makeStudyPlan().require()
По нажатию нужно вести на `https://hyperskill.org`

2022-08-29 07:06 UTC, vladkash commented
@ivan-magda есть ли сейчас смысл в StepQuizActionButtonCodeQuizDelegate?

2022-08-31 15:34 UTC, ivan-magda commented
> @ivan-magda есть ли сейчас смысл в StepQuizActionButtonCodeQuizDelegate?

Да, он нам нужен так как нужно переопределять текст и иконку для кнопки в состояниях отличных от `correct`. Внес правки.

2022-08-31 15:37 UTC, ivan-magda approved these changes

2022-08-31 15:40 UTC, merged