ALTAPPS-252: Android Improve States After Problem Of The Day Is Completed
hyperskill/mobile-app pull request #144
Opened 2022-08-24 13:27 UTC by eqimd

Task: [#ALTAPPS-252](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-252)

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Improve States After Problem Of The Day Is Completed

2022-08-24 13:28 UTC, eqimd commented
В процессе оказалось, что поле `step.secondsToComplete` при состоянии задачи дня `NeedToSolve` не обязательно присутствует. Сразу же пофиксил это.

2022-08-24 14:19 UTC, ivan-magda requested changes

2022-08-24 14:19 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt
> +        if (state is HomeFeature.ProblemOfDayState.Solved || state is HomeFeature.ProblemOfDayState.Empty) {
Уточняю нужно ли отображать кнопку в пустом состоянии https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-252/Android-Improve-states-after-Problem-of-the-day-is-completed#focus=Comments-74-184738.0-0

2022-08-24 14:19 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt
> +            intent.data = Uri.parse(BuildKonfig.BASE_URL)
Уточняю куда нужно вести по нажатии, на root или на study plan https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-252/Android-Improve-states-after-Problem-of-the-day-is-completed#focus=Comments-74-184738.0-0

2022-08-24 14:19 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt
> +                if (submissionStatus == SubmissionStatus.CORRECT) {
На сколько я понимаю кнопка `stepQuizSubmitButton` всегда в состоянии при верном решении будет активна и вести по нажатию на домашний экран. По описанию задачи требуется **после верного решения задачи дня** вместо кнопки Send отображать активную зеленую кнопку Continue, а по нажатию на нее вести на Home screen.

Я понимаю, что в MVP пользователь сможет решать только задачи дня, но в будущем функционал будет расширяться. Давай сделаем это только после верного решения задачи дня, что скажешь? Для этого нужно будет пробросить `dailyStepId` где-нибудь в state в shared модуле или по нажатию на кнопку на карточке задачи дня, которая ведёт на экран задачи при создании фрагмента передать в параметре флаг, что решается задача дня.

2022-08-24 14:22 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt
> +        if (state is HomeFeature.ProblemOfDayState.Solved || state is HomeFeature.ProblemOfDayState.Empty) {
@eqimd да, все верно, нужно отображать в обоих состояниях

2022-08-24 14:23 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt
> +            intent.data = Uri.parse(BuildKonfig.BASE_URL)
@eqimd все верно, нужно вести на https://hyperskill.org

2022-08-24 14:27 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt
> +                if (submissionStatus == SubmissionStatus.CORRECT) {
@eqimd если сделать это только после верного решения задачи дня будет нетривиально, то можно оставить как есть.

2022-08-24 14:29 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt
> -        if (state is HomeFeature.ProblemOfDayState.Solved || state is HomeFeature.ProblemOfDayState.Empty) {
Егор обновил описание задачи, нужно отображать в обоих состояниях, как у тебя было изначально https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-252

2022-08-24 20:33 UTC, eqimd commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt
> -        if (state is HomeFeature.ProblemOfDayState.Solved || state is HomeFeature.ProblemOfDayState.Empty) {
Кнопка сейчас отображается всегда, т.е. при любом из трёх состояний. Её надо отображать только при каких-то конкретных?

2022-08-25 08:16 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt
> -        if (state is HomeFeature.ProblemOfDayState.Solved || state is HomeFeature.ProblemOfDayState.Empty) {
@eqimd `state is HomeFeature.ProblemOfDayState.Solved || state is HomeFeature.ProblemOfDayState.Empty`

2022-08-25 09:53 UTC, ivan-magda approved these changes

2022-08-25 10:11 UTC, merged