ALTAPPS-283: Update placeholder screen
hyperskill/mobile-app pull request #151
Opened 2022-08-29 13:45 UTC by eqimd

Task: [#ALTAPPS-283](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-283)

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Add sign in button and deauthorize on click
- Update texts

2022-08-29 16:02 UTC, ivan-magda requested changes
При клике на кнопку _Sign in_ ничего не происходит (экран логина не открывается), по крайней мере когда пользователь не авторизован, при переходе с экрана онбординга при первом старте приложения.

2022-08-30 10:21 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/PlaceholderNewUserFragment.kt
> +    private lateinit var authorizationFlow: MutableSharedFlow<UserDeauthorized>
можно удалить, если не используется

2022-08-30 10:22 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/PlaceholderNewUserFragment.kt
> +                profileInteractor.clearCache()
еще нужно вызывать `authInteractor.clearCache()`

2022-08-30 11:06 UTC, eqimd commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/PlaceholderNewUserFragment.kt
> +                profileInteractor.clearCache()
почему кстати про логауте оно не вызывается?

2022-08-30 11:09 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/PlaceholderNewUserFragment.kt
> +                profileInteractor.clearCache()
оно в `AppActionDispatcher` вызывается во flow

2022-08-30 11:23 UTC, eqimd commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/PlaceholderNewUserFragment.kt
> +                profileInteractor.clearCache()
если я вызываю `authInteractor.clearCache()`, то что-то ломается -- после логина не меняется экран, нужно перезапустить приложение, чтоб все заработало
точно ли его надо вызывать?

2022-08-30 11:27 UTC, eqimd commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/PlaceholderNewUserFragment.kt
> +                profileInteractor.clearCache()
я сделал `emit()` во flow, с ним все работает, проверь еще раз

2022-08-30 11:37 UTC, ivan-magda approved these changes

2022-08-30 11:41 UTC, merged