ALTAPPS-280: shared add feedback email strings
hyperskill/mobile-app pull request #162
Opened 2022-08-31 09:22 UTC by vladkash

Task: [#ALTAPPS-](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-)

**Dependencies**
- !

**Reviewers**
- [ ] @eqimd 
- [ ] @ivan-magda 

**Description**
- Added strings for feedback email

2022-08-31 10:36 UTC, eqimd approved these changes

2022-08-31 11:55 UTC, ivan-magda requested changes

2022-08-31 11:55 UTC, ivan-magda commented on shared/src/commonMain/resources/MR/base/strings.xml
> +    <string name="feedback_email_text">\n\n\n---\nUser ID: %s\nApp version: %s\nDevice: %s</string>
Хочется, чтобы шаблон письма форсировался в shared, для примера UserAgentInfo, вот ещё для референса PR из Stepik https://github.com/stepicorg/stepik-android/pull/925

2022-08-31 18:40 UTC, ivan-magda commented on shared/src/commonMain/resources/MR/base/strings.xml
> +    <string name="feedback_email_text">\n\n\n---\nUser ID: %s\nApp version: %s\nDevice: %s</string>
что-то типо такого:
```kotlin
data class FeedbackEmailData(
    val mailTo: String,
    val subject: String,
    val body: String
)

object FeedbackEmailDataBuilder {
    fun build(
        applicationName: String,
        platform: Platform,
        userId: Long,
        applicationVersion: String
    ): FeedbackEmailData {
        val subject = "[$applicationName] ${platform.name} Feedback"

        val body = "\n\n\n---\nUser ID: $userId\nApp version: $applicationVersion\nDevice: ${platform.platform}"

        return FeedbackEmailData(
            mailTo = BuildKonfig.SUPPORT_EMAIL, // Need to be added to /shared/keys/*.properties
            subject = subject,
            body = body
        )
    }
}
```

и в `ProfileSettingsFeature` предоставлять эти данные

2022-09-01 09:23 UTC, vladkash commented
@ivan-magda я только не нашел красивого способа в shared модуле получить название приложения, которое есть на платформах в strings.xml (Android) и Info.plist (iOS)

2022-09-01 09:40 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/injection/ProfileSettingsComponentImpl.kt
> +            "My Hyperskill",
Давай пока положим в `BuildKonfig`, также как и `BuildKonfig.SUPPORT_EMAIL`

2022-09-01 09:43 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/injection/FeedbackEmailDataBuilder.kt
> +        val body = "\n\n\n---\nUser ID: $userId\nApp version: $applicationVersion\nDevice: ${platform.platform}"
`$userId` -> `${userId ?: "None"}`

2022-09-01 09:44 UTC, ivan-magda approved these changes

2022-09-01 09:45 UTC, ivan-magda commented
@vladkash оставил мелкие замечания и после можно мерджить

2022-09-01 09:58 UTC, merged