ALTAPPS-254: iOS UI improvements
hyperskill/mobile-app pull request #189
Opened 2022-10-03 12:12 UTC by vladkash

Task: [#ALTAPPS-254](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-254)

**Dependencies**
- !

**Reviewers**
- [x] @ivan-magda 

**Description**
- Блок об отсутствии поддержки типа задач перенесен перед описанием задачи
- Добавлена заглушка network error для темной темы
- Поднял цвет для рамок до alpha12 (так в дизайне), лучше стало, но не существенно, думаю нужно заводить еще ярче цвет, типа alpha20
- Заменил иконку стрика для темной темы
- Заменил иконку гемов для темной темы
- Сделал заново pod install (с текущим lock файлом у меня вылетала ошибка для версии AppAuth)

2022-10-03 12:17 UTC, ivan-magda commented
@vladkash 
> Сделал заново pod install (с текущим lock файлом у меня вылетала ошибка для версии AppAuth)

Откати изменения в `Podfile.lock` и выполни команду `pod install --repo-update`

2022-10-04 11:52 UTC, ivan-magda requested changes

2022-10-04 11:52 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift
> +            if case .unsupported = quizType {} else {
Давай так в одну строку не будем делать:
```swift
if case .unsupported = quizType {
    // it's rendered before step text
} else {
    ...
}
```

2022-10-04 11:52 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift
> +            if case .unsupported = quizType {} else {
Также можно расширить `StepQuizChildQuizType` добавив вычесляемую булевую переменную, которая будет возвращать значение о том поддерживается ли тип задачи или нет. Тогда условие можно будет упростить
```swift
if quizType.isSupported {
    ...
} else {
    ...
}
```

2022-10-05 04:46 UTC, vladkash commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift
> +            if case .unsupported = quizType {} else {
Сделл вариант с комментарием

2022-10-05 06:40 UTC, ivan-magda approved these changes

2022-10-05 07:31 UTC, merged