ALTAPPS-294: Fix iOS infinite loading after log out
hyperskill/mobile-app pull request #194
Opened 2022-10-06 17:30 UTC by ivan-magda

Task: [#ALTAPPS-294](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-294)

**Reviewers**
- [ ] @vladkash 

**Description**
- Partial migration to UIKit navigation
- Migrates app module, tab bar, and tab views

2022-10-07 09:46 UTC, vladkash requested changes

2022-10-07 09:46 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/main/presentation/AppReducer.kt
> +                        if (state.isNewUser) emptySet() else setOf(Action.ViewAction.NavigateTo.OnboardingScreen)
У меня при выходе из профиля чистится кеш, но не открывается экран авторизации

2022-10-07 09:52 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/main/presentation/AppReducer.kt
> +                        if (state.isNewUser) emptySet() else setOf(Action.ViewAction.NavigateTo.OnboardingScreen)
@vladkash а можешь пожалуйста сделать запись экрана, чтобы мне было понятнее, что происходит 🤔

2022-10-08 05:20 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/main/presentation/AppReducer.kt
> +                        if (state.isNewUser) emptySet() else setOf(Action.ViewAction.NavigateTo.OnboardingScreen)
@ivan-magda точно подтянул, все равно так же работает

2022-10-08 06:40 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/main/presentation/AppReducer.kt
> +                        if (state.isNewUser) emptySet() else setOf(Action.ViewAction.NavigateTo.OnboardingScreen)
@vladkash попробуй еще раз, пушнул

2022-10-09 04:14 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/main/presentation/AppReducer.kt
> +                        if (state.isNewUser) emptySet() else setOf(Action.ViewAction.NavigateTo.OnboardingScreen)
@ivan-magda ура, заработало)

2022-10-09 04:14 UTC, vladkash approved these changes

2022-10-09 06:40 UTC, merged