ALTAPPS-327: shared comments component realization
hyperskill/mobile-app pull request #195
Opened 2022-10-07 05:18 UTC by vladkash

Task: [#ALTAPPS-](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-)

**Dependencies**
- !

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Added comments component with necessary methods for hints

2022-10-07 09:46 UTC, ivan-magda requested changes

2022-10-07 09:46 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/core/injection/AppGraph.kt
> +    fun buildCommentsComponent(): CommentsComponent
Давай переименуем в `buildCommentsDataComponent`, т.к. в будущем этот модуль будет только предоставлять возможность работы с APIs. Сами хинты и форум решений будут полноценными фичами с состояниями, сообщениями и UI.

2022-10-07 09:46 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/comments/domain/interactor/CommentsInteractor.kt
> +    suspend fun createReaction(commentID: Long, reaction: String) {
Давай `reaction` опишем с помощью `enum` с возможными перечислениями и где у перечислений будет `raw value` типа String.

2022-10-07 09:46 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/comments/domain/interactor/CommentsInteractor.kt
> +    suspend fun createReaction(commentID: Long, reaction: String) {
или параметр `reaction: String` это на самом деле какой-то ID?

2022-10-07 09:46 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/comments/data/repository/CommentsRepositoryImpl.kt
> +            .getDiscussions("step", stepID, "hint", "popular", false)
при вызове `.getDiscussions("step", stepID, "hint", "popular", false)` сложно понять значение каждого параметра

давай вызовем так:
```kotlin
.getDiscussions(
    targetType = "step",
    targetID = stepID,
    thread = "hint",
    ordering = "popular",
    isSpam = false
)
```

2022-10-07 09:46 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/comments/data/repository/CommentsRepositoryImpl.kt
> +        commentsRemoteDataSource.createLike("abuse", "comment", commentID, 1)
также значение параметров неочевидно:
```kotlin
commentsRemoteDataSource.createLike(subject = "abuse", targetType = "comment", targetID = commentID, value = 1)
```

2022-10-07 09:46 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/comments/injection/CommentsComponent.kt
> +interface CommentsComponent {
CommentsDataComponent

2022-10-07 09:46 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/comments/remote/model/CommentDetailsResponse.kt
> +class CommentDetailsResponse(
может быть просто `CommentsResponse`

2022-10-10 11:56 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/comments/domain/interactor/CommentsInteractor.kt
> +    suspend fun createReaction(commentID: Long, reaction: String) {
да, там два варианта всего, я в задаче невнимательно посмотрел, думал любой эмодзи можно передать

2022-10-10 11:58 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/comments/domain/interactor/CommentsInteractor.kt
> +    suspend fun createReaction(commentID: Long, reaction: String) {
> да, там два варианта всего, я в задаче невнимательно посмотрел, думал любой эмодзи можно передать

OK, тогда здесь кажется хорошо `enum` подойдет.

2022-10-10 12:08 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/comments/domain/model/Reaction.kt
> +enum class Reaction(val rawValue: String) {
refactor rename `Reaction` -> `ReactionType`

2022-10-10 12:09 UTC, ivan-magda approved these changes

2022-10-10 12:26 UTC, merged