ALTAPPS-370: iOS step quiz hints view
hyperskill/mobile-app pull request #215
Opened 2022-11-04 08:41 UTC by vladkash

Task: [#ALTAPPS-](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-)

**Dependencies**
- !

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Added iOS view for step quiz hints feature

2022-11-04 08:43 UTC, vladkash commented
@ivan-magda я не сделал еще аналитику и кнопочку Show more, чтобы раскрывать полный комментарий. По аналитике я посмотрю на другие модули, как делалось, а с раскрытием комментария думаю просто добавить локальную булевую переменную и в зависимости от нее показывать кнопку и обрезанный до какого-то фиксированного значения текст. Пойдет?

2022-11-04 08:50 UTC, ivan-magda commented
@vladkash

> я не сделал еще аналитику, по аналитике я посмотрю на другие модули, как делалось

OK, если что спрашивай 

> я не сделал еще кнопочку Show more, чтобы раскрывать полный комментарий. С раскрытием комментария думаю просто добавить локальную булевую переменную и в зависимости от нее показывать кнопку и обрезанный до какого-то фиксированного значения текст. Пойдет?

Да, думаю можно просто во `View` добавить `@State var showingMore = false`. Если реализовать обрезанный до какого-то фиксированного значения текст будет сложно, то можно будет вынести в отдельную задачу на будущую доработку, это не так важно.

2022-11-04 09:35 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/StepQuizHintsViewModel.swift
> +> {
Здесь вместо табуляции 2 пробела

```suggestion
final class StepQuizHintsViewModel: FeatureViewModel<
  StepQuizHintsFeatureState,
  StepQuizHintsFeatureMessage,
  StepQuizHintsFeatureActionViewAction
> {
```

2022-11-04 09:37 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/Views/StepQuizHintsView.swift
> +            .onAppear {
еще `onDisappear`:
```swift
.onDisappear(perform: viewModel.stopListening)
```

2022-11-04 09:46 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/Views/StepQuizHintCardView.swift
> +                        .foregroundColor(Color(ColorPalette.black900Alpha60))
В дизайне используется цвет `colorOnSurface_0.6` и у нас есть `Color.secondaryText`.
Можно заменить на:
```suggestion
                        .foregroundColor(.secondaryText)
```

2022-11-04 09:46 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/Views/StepQuizHintCardView.swift
> +                        .foregroundColor(Color(ColorPalette.black900Alpha60))
И везде такой цвет можно заменить

2022-11-04 09:48 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/Views/StepQuizHintCardView.swift
> +                    .foregroundColor(Color(ColorPalette.black900Alpha38))
В дизайне используется цвет `colorOnSurface_0.38` и у нас есть цвет для этого `Color.disabledText`.
Можно заменить на:
```suggestion
                    .foregroundColor(.disabledText)
```

И везде такие цвета пробегись замени если что.

2022-11-04 09:51 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/Views/StepQuizHintCardView.swift
> +        .background(Color(ColorPalette.background))
```suggestion
        .background(Color.background)
```

2022-11-04 09:56 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/Views/StepQuizHintReactionButtonView.swift
> +        )
Давай добавим **bounce** анимацию:
```swift
.buttonStyle(BounceButtonStyle(bounceScale: 0.75))
```

2022-11-04 09:59 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/Views/StepQuizShowHintButton.swift
> +        let buttonHeight: CGFloat = 34
refactor rename buttonMinHeight

2022-11-04 10:04 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/domain/interactor/StepQuizHintsInteractor.kt
> +        return commentsDataInteractor.getHintsIDs(stepId).filter { seenHintsIds?.contains(it)?.not() ?: true }
Давай в несколько строк:
```suggestion
        return commentsDataInteractor
            .getHintsIDs(stepId)
            .filter { seenHintsIds?.contains(it)?.not() ?: true }
```

2022-11-04 10:19 UTC, ivan-magda commented
@vladkash я логику работы бизнес требований не проверял, команда тестирования уже будет это проверять. Все ОК, оставил незначительные комментарии.

В дополнение к доработкам о которых ты писал, не забудь что нужно будет написать документацию о том как использовать **shared логику** в задачу [ALTAPPS-328](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-328).

Еще так как у нас есть **OKR** про техническую документацию, то было бы круто задокументировать `StepQuizHintsFeature`. Для этого советую установить [kdoc-generator](https://plugins.jetbrains.com/plugin/10389-kdoc-generator) плагин:
1. Launch Android Studio application
2. Choose **File -> Settings**
3. Search for **kdoc-generator** plugin

2022-11-07 12:12 UTC, ivan-magda requested changes

2022-11-07 12:12 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsFeature.kt
> +        object ReportHintReportShownEventMessage : Message
`ReportHintNoticeShownEventMessage`

2022-11-07 12:12 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsFeature.kt
> +        object ReportHintNoticeHiddenEventMessage : Message
`ReportHintNoticeHiddenEventMessage` и почему-то не передаётся результат "yes"/"no"

2022-11-07 12:12 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsReducer.kt
> +                            )
Здесь нужно удалить, смотри комментарий про `ReportHintNoticeHiddenEventMessage`, нужно переделать в `data class` и передавать результат "yes"/"no"

2022-11-07 12:12 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsReducer.kt
> +                                isReported = false
`isReported` должно передаваться в сообщении

2022-11-07 12:12 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsReducer.kt
> +        else HyperskillAnalyticRoute.Learn.Step(currentStepId)
```kotlin
private fun resolveAnalyticRoute(currentStepId: Long, dailyStepId: Long?): HyperskillAnalyticRoute =
    if (currentStepId == dailyStepId) HyperskillAnalyticRoute.Learn.Daily(currentStepId)
    else HyperskillAnalyticRoute.Learn.Step(currentStepId)
```

2022-11-08 09:12 UTC, vladkash commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/Views/StepQuizHintCardView.swift
> +                        onHintReportModalAppear()
мне больше нравится твой способ

2022-11-08 09:24 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsFeature.kt
> +        object ReportSeeHintClickedEventMessage : Message
@ivan-magda 
LoadHintButtonClicked вызывается не только для подгрузки первого хинта при нажатии See hint, но и при загрузке всех следующих при нажатии See next hint. Я думаю в аналитику надо отправлять именно первое нажатие, исходя из target, поэтому нужно это дополнительное сообщение. Если я не прав - поправь меня плиз

2022-11-08 09:29 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsFeature.kt
> +        object ReportHintNoticeHiddenEventMessage : Message
@ivan-magda 
не передается, потому что при yes вызывается сообщение HintReported и вызов экшена происходит там, это же событие вызывается только при нажатии на no. Или правильней перенести этот параметр в данное сообщение и вызывать экшен только здесь?

2022-11-08 09:30 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsFeature.kt
> +        object ReportSeeHintClickedEventMessage : Message
@vladkash 
В аналитику нужно отправлять нажатие на кнопку "**See hint**", а также нажатие на кнопку "**See next hint**". Если для этого нужно дополнительное сообщение, то OK.

2022-11-08 09:45 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/Views/StepQuizHintsView.swift
> +                hasNextHints: state.hintsIds.isEmpty,
Кажется здесь должно быть условие `!state.hintsIds.isEmpty`

2022-11-08 09:50 UTC, ivan-magda commented
@vladkash в `CommentsRemoteDataSourceImpl.createReaction` должен отправляться POST запрос, а сейчас GET.

2022-11-08 09:53 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsFeature.kt
> +        object ReportSeeHintClickedEventMessage : Message
@ivan-magda а они различаться должны таргетами или нет? Типа у нас есть target "see_hint", нужно его же слать на "See next hint" или правильно добавить новый "see_next_hint"?

2022-11-08 10:00 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsFeature.kt
> +        object ReportSeeHintClickedEventMessage : Message
@vladkash 
В вебе для обоих кнопок отправляется один и тот же таргет "see_hint", но я думаю это ошибка и нужно при нажатии на кнопку See hint отправлять таргет "see_hint", а при нажатии на кнопку See next hint таргет "see_next_hint".
На сколько я помню таргет в аналитике для кнопки просто определяется по тексту на кнопке, ну и чуть в другом формате (lowercase и _)

2022-11-08 10:17 UTC, ivan-magda approved these changes

2022-11-08 10:35 UTC, merged