ALTAPPS-393: iOS topics repetitions views
hyperskill/mobile-app pull request #224
Opened 2022-11-15 12:03 UTC by vladkash

Task: [#ALTAPPS-393](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-393)

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Added views for topics repetitions feature

2022-11-15 14:42 UTC, ivan-magda commented
@vladkash зафейлилась проверка https://github.com/hyperskill/mobile-app/actions/runs/3470317274/jobs/5798378320, что-то не то с ресурсом `topics_repetitions_explanation_title`.

2022-11-16 09:00 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/RepetitionsChartView.swift
> +                .foregroundColor(.primaryText)
еще добавить `.bold()`

2022-11-16 09:04 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/RepetitionsChartView.swift
> +        VStack(alignment: .center, spacing: LayoutInsets.smallInset) {
```suggestion
        VStack(alignment: .center, spacing: LayoutInsets.defaultInset) {
```

2022-11-16 09:06 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/RepetitionsChartView.swift
> +                        .padding(.leading, RepetitionsChartBar.Appearance().labelWidth + LayoutInsets.smallInset + 2)
лучше этот паддинг вынести в Appearance

2022-11-16 09:10 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/RepetitionsChartView.swift
> +                    RepetitionsChartBar(label: formatter.timesCount(times), value: count, maxValue: roundedMaxCount)
Кажется неверно расчитывается ширина прогресс бара с `39`, он должен быть ближе к 40, чем сейчас. Но если это фиксить будет сложно, то не критично:
<img width="386" alt="Screen Shot 2022-11-16 at 1 08 44 PM" src="https://user-images.githubusercontent.com/8586063/202138075-a8d4682d-878e-495f-a35a-6dcbaa123d8f.png">

2022-11-16 09:17 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/RepetitionsExplanationView.swift
> +                .foregroundColor(.primaryText)
еще добавить `.bold()`

2022-11-16 09:18 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/TopicsToRepeatView.swift
> +                .foregroundColor(.primaryText)
еще добавить `.bold()`

2022-11-16 11:41 UTC, vladkash commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/TopicsRepetitionsCardView.swift
> +        let spacing: CGFloat = 12
но в дизайне 12)))

2022-11-16 11:44 UTC, vladkash commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/TopicsToRepeatView.swift
> +                    ForEach(topics, id: \.self) { topic in
Я это все пока сделал чисто как заглушку, потом будет нормальная структура с хоть какими-то идентификаторами, которые можно будет использовать

2022-11-16 11:57 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/TopicsRepetitionsCardView.swift
> +        let spacing: CGFloat = 12
@vladkash у нас на всех остальных карточках домашнего экрана используется `LayoutInsets.defaultInset`, как по гайдлайнам iOS - отступ от контейнера должен быть `16`,  я уже много раз говорил команде дизайна, что лучше следовать гайдлайнам и использовать стандартные отступы.

2022-11-16 14:15 UTC, ivan-magda requested changes

2022-11-16 14:15 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/TopicsRepetitionsView.swift
> +                TopicsRepetitionsChartBlock(topicsToRepeatCount: topicsToRepeatCount)
давай для `TopicsRepetitionsChartBlock` добавим отступ сверху, чтобы было расстояние между navigation bar `.padding(.top, LayoutInsets.largeInset)`

2022-11-16 14:15 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/TopicsRepetitionsView.swift
> +                    .padding(.bottom)
`.padding(.bottom, LayoutInsets.largeInset)`, чтобы отспуты между блоками были одинаковыми и после этого изменения в `TopicsRepetitionsView` отступ `LayoutInsets.largeInset` будет встречаться уже 3 раза, поэтому можно вынести в `Appearance`, чтобы не было дублирования.

2022-11-16 14:15 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/TopicsRepetitionsView.swift
>          .background(Color(ColorPalette.background))
в темной теме этот `background` выглядит странно (получается 3 цвета одновременно задействовано). Давай сделаем `background` как на табах (Home, Track, Profile) - `.background(Color.systemGroupedBackground)`.


![Simulator Screen Shot - iPhone 14 Pro - 2022-11-16 at 18 03 38](https://user-images.githubusercontent.com/8586063/202202594-44470e06-bc6e-4628-a50c-c00ef178e978.png)

2022-11-16 15:18 UTC, ivan-magda approved these changes
Job'a зафейлилась https://github.com/hyperskill/mobile-app/actions/runs/3480421650/jobs/5820201902#step:4:1402
```
/Users/runner/work/mobile-app/mobile-app/iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/Views/HomeView.swift:119:13: switch must be exhaustive
[15:00:06]: ▸             switch HomeFeatureActionViewActionNavigateToKs(navigateToViewAction) {
```

2022-11-16 16:40 UTC, merged