Feature/altapps 390/android forward session on continue in the web
hyperskill/mobile-app pull request #240
Opened 2022-11-23 14:26 UTC by XanderZhu

Task: [#ALTAPPS-390](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-390/Android-Forward-session-on-continue-in-the-Web)

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Implement magicLink request and related loading and error showing in shared code
- Implement Android UI for magicLink request

2022-11-23 21:01 UTC, ivan-magda commented
Зафейлилась [ktlint job](https://github.com/hyperskill/mobile-app/actions/runs/3532908332/jobs/5927855514), нужно будет пофиксить:
```
> Task :shared:ktlintCommonMainSourceSetCheck FAILED
/home/runner/work/mobile-app/mobile-app/shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt:11:1 Wildcard import (cannot be auto-corrected)
/home/runner/work/mobile-app/mobile-app/shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserReducer.kt:47:15 Unexpected spacing after "("
/home/runner/work/mobile-app/mobile-app/shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserReducer.kt:47:35 Unexpected spacing after ")"
/home/runner/work/mobile-app/mobile-app/shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserReducer.kt:47:35 Unexpected spacing before ")"
/home/runner/work/mobile-app/mobile-app/shared/src/commonMain/kotlin/org/hyperskill/app/track/presentation/TrackActionDispatcher.kt:64:1 Unexpected blank line(s) before "}"
```

Вот так можно локально запустить проверку `./gradlew ktlintCheck`.

2022-11-23 21:39 UTC, ivan-magda commented
На данный момент индикатор создания `MagicLink` выглядит странно, сливается с основным контентом экрана:

<img src="https://user-images.githubusercontent.com/8586063/203649940-be6c02d5-6fe6-4fc7-b5ce-4bce32c795d9.png" alt="Screenshot_20221124_013046" width="30%"/>

Можем ли этот индикатор обернуть в карточку, как ниже (только без заголовка и сообщения)?

<img src="https://user-images.githubusercontent.com/8586063/203650319-e4dfe1e0-c2d8-4d44-9d45-6e5ed75c2b17.png" alt="Screenshot_20221124_013150" width="30%"/>

2022-11-23 22:36 UTC, ivan-magda commented
> На данный момент индикатор создания `MagicLink` выглядит странно, сливается с основным контентом экрана:
> 
> <img alt="Screenshot_20221124_013046" width="30%" src="https://user-images.githubusercontent.com/8586063/203649940-be6c02d5-6fe6-4fc7-b5ce-4bce32c795d9.png">
> 
> Можем ли этот индикатор обернуть в карточку, как ниже (только без заголовка и сообщения)?
> 
> <img alt="Screenshot_20221124_013150" width="30%" src="https://user-images.githubusercontent.com/8586063/203650319-e4dfe1e0-c2d8-4d44-9d45-6e5ed75c2b17.png">

Я бы на самом деле сделал единый UI-компонент `CreateMagicLinkProgressIndicator` и заиспользовал его во всех остальных модулях, но если так сделать займет ощутимо времени, то лучше это отложить на будущее в качестве доработки, т.к. сейчас важнее сама реализация проброса авторизации.

2022-11-23 22:59 UTC, ivan-magda requested changes

2022-11-23 22:59 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthCredentialsFeature.kt
> +        val isLinkLoadingShown: Boolean = false
Давай `isLinkLoadingShown` переименуем в `isLoadingMagicLink`, чтобы было понятнее о чем идет речь. И в остальных модулях тоже.

2022-11-23 22:59 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/magic_links/domain/interactor/UrlPathProcessor.kt
> +class UrlPathProcessor(private val magicLinksInteractor: MagicLinksInteractor) {
На данный момент можно было не выносить логику по обработке `HyperskillUrlPath` и созданию `MagicLink` в `UrlPathProcessor`, а оставить ее в интеракторе, т.к. мы все равно пока что умеем работать только c `next url path`, но как заготовка на будущее хорошо.

2022-11-23 22:59 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthCredentialsFeature.kt
> +        data class LinkReceived(val url: String) : Message
Давай `LinkReceived` переименуем в `GetMagicLinkReceiveSuccess` и в остальных модулях тоже.

2022-11-23 22:59 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthCredentialsFeature.kt
> +        object LinkReceiveFailed : Message
Давай `LinkReceiveFailed` переименуем в `GetMagicLinkReceiveFailure` и в остальных модулях тоже.

2022-11-23 22:59 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthCredentialsFeature.kt
> +        data class GetLink(val path: HyperskillUrlPath) : Action
Давай `GetLink` переименуем в `GetMagicLink` и в остальных модулях тоже.

2022-11-23 22:59 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthCredentialsFeature.kt
> +            data class FollowLink(val url: String) : ViewAction
Давай `FollowLink` переименуем в `OpenUrl` и в остальных модулях тоже.

2022-11-23 22:59 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthCredentialsFeature.kt
> +            object ShowFollowLinkError : ViewAction
Давай `ShowFollowLinkError` переименуем в `ShowGetMagicLinkError` и в остальных модулях тоже.

2022-11-23 22:59 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthCredentialsFragment.kt
> -        }
👍

2022-11-23 22:59 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthCredentialsFragment.kt
> +    private fun renderFormState(state: AuthCredentialsFeature.State) {
Получается несоответствие между названием функции и типом передаваемого параметра (`formState` -> `state`), может лучше дополнительно в параметре передать `isLinkLoadingShown`?

2022-11-23 22:59 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt
> +                // just do nothing
OK, мы обычно а таких ситуациях оставляем комментарий `// no op`

2022-11-23 22:59 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthCredentialsActionDispatcher.kt
> +    ) {
Если честно не очень понимаю зачем это нужно было выносить в отдельную функцию (и в остальных модулях также), ведь можно было все сделать на месте при обработке `Action.GetLink`

2022-11-23 22:59 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthCredentialsReducer.kt
> +            is Message.ClickedResetPassword -> {
`ClickedResetPassword` сообщает нам о нажатии на кнопку сброса пароля, поэтому нет необходимости в сообщении `Message.ClickedResetPasswordEventMessage`. `Message.ClickedResetPasswordEventMessage` можно удалить, а при обработке `Message.ClickedResetPassword` дополнительно передавать евент в аналитику.

Также посмотри в остальных модулях, видел аналогичные ситуации.

2022-11-23 22:59 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/track/view/fragment/TrackFragment.kt
> +            TrackFeature.Action.ViewAction.ShowFollowLinkError ->
Заметил, что ты при использовании `when` во многих местах опускаешь использование `is`, почему?

2022-11-24 08:16 UTC, XanderZhu commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt
> +                // just do nothing
Окей, принял 
Я это добавляю, так как в будущем non exhausted when будет выдавать error.

2022-11-24 08:17 UTC, XanderZhu commented on shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthCredentialsActionDispatcher.kt
> +    ) {
Я это вынес, чтобы  корневой when было проще читать. Если в when добавляется много логики, то по-моему читать становится сложнее.

2022-11-24 08:21 UTC, XanderZhu commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/track/view/fragment/TrackFragment.kt
> +            TrackFeature.Action.ViewAction.ShowFollowLinkError ->
Для object is не нужен.
Но в случае, если мы object п переделаем в class, то придется добавить is.

2022-11-24 09:00 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt
> +                // just do nothing
Ага, спасибо!

2022-11-24 09:07 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthCredentialsActionDispatcher.kt
> +    ) {
Ага, понял 👍 Давай пока так не будем делать, будем придерживаться текущего написания всего в корневом when. В тех случаях, когда действительно будет сложно читать, то будем дробить. И еще такой подход нужно будет обсудить, всей командой, чтобы каждый понимал зачем и почему, и обновить наш Kotlin Style Guide.

2022-11-24 09:19 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/track/view/fragment/TrackFragment.kt
> +            TrackFeature.Action.ViewAction.ShowFollowLinkError ->
OK, понял. А есть ли от этого какой-то профит или это просто стилистически?

Давай хотя бы в редюсерах всегда писать с использованием `is`, даже если в этом нет необходимости, потому что складывается впечатление как будто-то обработка сообщений наезжает друг на друга (типо после обработки `ClickedContinueLearningOnWebEventMessage` дополнительно может выполнится `ClickedContinueLearningOnWeb`), alignment в редюсерах пропадает:

<img width="820" alt="Screen Shot 2022-11-24 at 1 18 53 PM" src="https://user-images.githubusercontent.com/8586063/203745117-ef42fd91-4246-4f55-8842-e8fc88659130.png">

2022-11-24 10:43 UTC, XanderZhu commented
> На данный момент индикатор создания `MagicLink` выглядит странно, сливается с основным контентом экрана:
> 
> <img alt="Screenshot_20221124_013046" width="30%" src="https://user-images.githubusercontent.com/8586063/203649940-be6c02d5-6fe6-4fc7-b5ce-4bce32c795d9.png">
> 
> Можем ли этот индикатор обернуть в карточку, как ниже (только без заголовка и сообщения)?
> 
> <img alt="Screenshot_20221124_013150" width="30%" src="https://user-images.githubusercontent.com/8586063/203650319-e4dfe1e0-c2d8-4d44-9d45-6e5ed75c2b17.png">

@ivan-magda Такой индикатор подойдет?
<img alt="2022-11-24 14 41 19" width="30%" src="https://user-images.githubusercontent.com/25664794/203764023-95c859df-5a71-4e42-81cb-372be2bac01c.jpg">

2022-11-24 10:50 UTC, XanderZhu commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/track/view/fragment/TrackFragment.kt
> +            TrackFeature.Action.ViewAction.ShowFollowLinkError ->
Да, можем всегда использовать is. Просто при автоподставновке все варитантов в when, is не проставляется для object вариантов.
По поводу alignment - можем в таких случаях просто использовать фигурные скобки.

2022-11-24 10:51 UTC, ivan-magda commented
> @ivan-magda Такой индикатор подойдет? <img alt="2022-11-24 14 41 19" width="30%" src="https://user-images.githubusercontent.com/25664794/203764023-95c859df-5a71-4e42-81cb-372be2bac01c.jpg">

Это лучше, а нельзя ли сделать так, чтобы сам прогресс индикатор был по центру и вокргу него было не так много отступов (чтобы был не длинный прямоугольник, а квадрат)?

Но тут тебе наверное будет веднее, как лучше сдлеать по гайдлайнам Google Material Design.

2022-11-24 10:57 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/track/view/fragment/TrackFragment.kt
> +            TrackFeature.Action.ViewAction.ShowFollowLinkError ->
> Просто при автоподставновке все варитантов в when, is не проставляется для object вариантов.

ага, действительно автоподставновка так делает

> Да, можем всегда использовать is.

Да, давай пока так и будем делать, а потом обсудим и обновим наш Kotlin Style Guide.

2022-11-24 10:59 UTC, XanderZhu commented
> > @ivan-magda Такой индикатор подойдет? <img alt="2022-11-24 14 41 19" width="30%" src="https://user-images.githubusercontent.com/25664794/203764023-95c859df-5a71-4e42-81cb-372be2bac01c.jpg">
> 
> Это лучше, а нельзя ли сделать так, чтобы сам прогресс индикатор был по центру и вокргу него было не так много отступов (чтобы был не длинный прямоугольник, а квадрат)?
> 
> Но тут тебе наверное будет веднее, как лучше сдлеать по гайдлайнам Google Material Design.

Вообще, это стандартный диалог из Material библиотеки. У него у него место для кастомного контента определено именно слева. Форма его тоже предопределена. Если нужно - можно сделать полностью алерт.
Но на мой взгляд, первый вариант, с текстом был более информативным для пользователя.

2022-11-24 11:04 UTC, ivan-magda commented
> Но на мой взгляд, первый вариант, с текстом был более информативным для пользователя.

Да давай так и сделаем 👍 Отобрази текст, который считаешь нужным.

2022-11-24 12:18 UTC, XanderZhu commented
@ivan-magda 
Исправил все замечания

2022-11-24 12:47 UTC, ivan-magda commented
> @ivan-magda Исправил все замечания

OK, спасибо! Я тогда сегодня постараюсь в iOS перейти на использование логики из shared-модуля и будем мерджить.

2022-11-24 17:25 UTC, ivan-magda approved these changes

2022-11-24 17:25 UTC, merged