ALTAPPS-412: shared topics repetitions fixes
hyperskill/mobile-app pull request #245
Opened 2022-11-28 10:39 UTC by vladkash

Task: [#ALTAPPS-412](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-412)

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Change label "1 time" -> "once" according to web
- Pass recommendedRepetitionsCount via Initialize message to avoid uneccessary network request

2022-11-28 17:42 UTC, ivan-magda requested changes

2022-11-28 17:42 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/Views/HomeView.swift
> +                }
`recommendedRepetitionsCount` лучше передать параметром в `HomeFeature.Action.ViewAction.NavigateTo.TopicsRepetitionsScreen`

2022-11-28 17:42 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/Views/HomeView.swift
> +                }
`recommendedRepetitionsCount` уже есть в `HomeFeature.State.Content`

2022-11-28 17:42 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/TopicsRepetitionsView.swift
> +    let recommendedRepetitionsCount: Int32
Лучше это хранить в `TopicsRepetitionsViewModel`, тогда сигнатура `viewModel.doLoadContent` ни как не изменится, ну и View не нужно знать об `recommendedRepetitionsCount`, который используется только при отправке Message.

2022-11-28 17:42 UTC, ivan-magda commented on shared/src/commonMain/resources/MR/base/plurals.xml
>      </plural>
Ломается смысл плюрализации `times`, `times` это общее название и допустим в будущем кто-то захочет воспользоваться данным ресурсом и результат будет не тем, что ожидаешь.

Будет лучше переименовать или добавить еще 1 ресурс, где явно будет указано, что этот ресурс следует использовать на графике повторения топиков.

2022-11-29 08:22 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/TopicsRepetitionsViewModel.swift
> +    let recommendedRepetitionsCount: Int32
private let

2022-11-29 08:22 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/HomeViewModel.swift
> +        if case .content(let homeFeatureStateContent) = stateKs {
А у нас в аналитику шлется событие о нажатии на виджет повторения на домашнем экране?

2022-11-29 14:24 UTC, vladkash commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/HomeViewModel.swift
> +        if case .content(let homeFeatureStateContent) = stateKs {
Да, я тут допустил ошибку, переписал через Message

2022-11-29 14:35 UTC, ivan-magda approved these changes

2022-11-29 15:05 UTC, merged