ALTAPPS-430: Show earned gems after completing Problem of the day
hyperskill/mobile-app pull request #247
Opened 2022-11-30 16:05 UTC by vladkash

Task: [#ALTAPPS-430](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-430)

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Added problem of day solved modal with gems count

2022-12-01 11:07 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift
> +        }
Не нравится необходимость в 2-х `State` переменных для того, чтобы показать модалку (хотя может это и не критично относительно обновления SwiftUI State). Еще я бы модификатор `panModal` применял не на root уровне, а там где описывается UI задачи `buildChildQuiz`.

Давай лучше сделаем в императивном стиле по аналогии с обработкой `StepQuizFeatureActionViewActionRequestUserPermission` так более проще даже получается. Нужно будет добавить функцию `presentDailyStepCompletedModal(gemsCount:)`. У `PanModalPresentableViewController` есть callback `onDisappear`, поэтому можно будет без проблем отправить в аналитику `hidden` событие. `PanModalPresenter` можно будет получить из `environmentObject` или создать в теле функции.

2022-12-01 11:09 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift
> +        case let showProblemOfDaySolvedModalViewAction as StepQuizFeatureActionViewActionShowProblemOfDaySolvedModal:
Это не критично (опционально) может сразу `handleViewAction` отрефакторить на `StepQuizFeatureActionViewActionKs` moko-kswift

2022-12-01 11:14 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizReducer.kt
> +                state to setOf(Action.ViewAction.ShowNetworkError)
Будет лучше, если мы не будем обрабатывать и показывать индикацию ошибки пользователю, потому что это действие было инициировано не им, а нами под капотом. Тем более это вызовет диссонанс - при верном решении тебе внезапно показывается индикатор ошибки, очень странно.

2022-12-01 11:22 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizFeature.kt
> +        object FetchGemsCount : Action
`FetchGemsCount` -> `FetchGemsCountAfterProblemOfDaySolved` или `FetchGemsCountWhenProblemOfDaySolved`

и пусть название длиннее, но зато сразу понятно, что делается, почему и когда

2022-12-02 07:48 UTC, vladkash commented on shared/src/commonMain/resources/MR/base/strings.xml
> +    <string name="problem_of_day_solved_modal_title">Problem of the day\nsolved!</string>
@ivan-magda  я когда делал без переноса строки у меня слово day уезжало на вторую строчку тоже, но по дизайну кажется так быть не должно( это можно на платформе как-то лучше сделать?

2022-12-02 09:00 UTC, ivan-magda commented on shared/src/commonMain/resources/MR/base/strings.xml
> +    <string name="problem_of_day_solved_modal_title">Problem of the day\nsolved!</string>
Дизайн нужен не для того, чтобы его пиксель в пиксель переносить 😀 Допустим, посмотри на Resizes макеты в Figma и ты там увидишь, что строка вообще должна быть без переноса на устройствах с большим экраном...

На сегодняшний день существует более 50 устройств от Apple и наверное с десяток различных размерностей экранов https://www.ios-resolution.com/, ты представь насколько нужно упароться, чтобы сделать так как тебе хочется.

> но по дизайну кажется так быть не должно( это можно на платформе как-то лучше сделать?

Мы просто отображаем текст, а дальше iOS уже сама решит, что и где нужно переносить. Не забывай, что в iOS есть динамические шрифты, scale самого интерфейса и много разных размерностей экранов, пусть система сама все разруливает.

2022-12-02 09:20 UTC, vladkash commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProblemOfDaySolvedModal/ProblemOfDaySolvedModalViewController.swift
> +        let gemsBadgeImageWidthHeight: CGFloat = 48
а дизайн поменяли похоже, иконки другие)

2022-12-02 10:54 UTC, vladkash commented
@ivan-magda я в целом все поправил, только возникли проблемы с тем, чтобы все запихать в вертикальный UIStackVIew. Можешь, пожалуйста, посмотреть ViewController и подсказать в какую строну копать, чтобы я поскорее сам исправил?

2022-12-02 11:14 UTC, vladkash commented on shared/src/commonMain/resources/MR/base/strings.xml
> +    <string name="problem_of_day_solved_modal_title">Problem of the day\nsolved!</string>
окей, сорян))))

2022-12-05 07:40 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj
> +				E9ACD33F293733F80005E05B /* ProblemOfDaySolvedModal */,
Почему-то перенеслось в модуль `Profile`

2022-12-05 07:40 UTC, ivan-magda commented
> @ivan-magda я в целом все поправил, только возникли проблемы с тем, чтобы все запихать в вертикальный UIStackVIew. Можешь, пожалуйста, посмотреть ViewController и подсказать в какую строну копать, чтобы я поскорее сам исправил?

поправил, посмотри

2022-12-05 08:06 UTC, ivan-magda requested changes

2022-12-05 12:04 UTC, vladkash commented
@ivan-magda как я понял кроме того, что ты убрал ненужные translatesAutoresizingMaskIntoConstraints и добавил ограничения по ширине/высоте где я этого не сделал, главное изменение это добавление вызова в main очереди GCD методов panModalSetNeedsLayoutUpdate и panModalTransition

2022-12-05 14:04 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizActionDispatcher.kt
> +                        .getCurrentProfile(sourceType = DataSourceType.REMOTE)
После верного решения каждый раз будет выполняться сетевой запрос, что не есть хорошо. Проверку на то является ли решенный шаг задачей дня можно сделать запросив пользователя из `DataSourceType.CACHE` или отправив message в Reducer и там разрулить.

2022-12-05 14:42 UTC, merged