ALTAPPS-437: new users track selection
hyperskill/mobile-app pull request #256
Opened 2022-12-07 10:17 UTC by vladkash

Task: [#ALTAPPS-437](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-437)

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Shared module implemented

2022-12-07 13:19 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserReducer.kt
> +                state to setOf(Action.ViewAction.NavigateTo.HomeScreen)
По хорошему здесь еще дополнительно нужно показать `ProgressHUD` с сообщением об успехе.

По итогу, в процессе выбора трека нам необходимо поддерживать 3 состояния:
1. `Loading` - ViewAction, который показывает ProgressHUD
2. `Success` - ViewAction, который показывает ProgressHUD с сообщением `Track successfully selected`
3. `Error` - ViewAction, который показывает ProgressHUD с сообщением `Failed to select track`

2022-12-07 13:19 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthNewUserPlaceholder/AuthNewUserPlaceholderView.swift
> +//        switch PlaceholderNewUserFeatureActionViewActionKs(viewAction) {
iOS специфичный код, который уже неактуален можно удалить, а Android пускай пока будет закомментирован, Саша разберется.

Я думаю, что этот PR мы не будем мерджить пока не будут готовы обе платформенные реализации на Android и iOS, чтобы в `develop` не сломать этот экран (вдруг эта задача затянется, а нам нужно будет релизиться, тогда возникнут неудобства), поэтому можно создавать ветки с UI реализациями от этой и далее мерджить сюда же.

2022-12-08 06:32 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/remote/ProfileRemoteDataSourceImpl.kt
> +                .put("/api/profiles/$profileId") {
Егор неверно указал, я использовал PUT потому что он был в документации и я заранее проверил, что он работает как ожидается

2022-12-08 06:40 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/track/remote/TrackRemoteDataSourceImpl.kt
> +                    }
@ivan-magda спасибо! Сделаю третий вариант, при этом page необязательно указывать, 1 используется по-умолчанию

2022-12-08 06:53 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserActionDispatcher.kt
> +                        projectId = action.track.projectsByLevel.easy?.firstOrNull() ?: DEFAULT_PROJECT_ID
На самом деле судя по поведению API бэкенд не проверяет, что выбранный проект совпадает с выбранным треком. Егор ответил, что нужно брать из следующих уровней сложности, но это не защищает нас от ситуации когда в треке нет проектов вообще (судя по текущей модели данных такое возможно). Наверное, я тогда покажу то же самое сообщение об ошибке как если бы запрос выполнился неверно

2022-12-08 07:42 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/track/remote/TrackRemoteDataSourceImpl.kt
> +                    parameter("page_size", TRACKS_PAGE_MAX_SIZE)
При вызове `getTracks(trackIds:)`, где `trackIds` пустой список я бы ожидал, что в результате вернется пустой список треков и по хорошему такой запрос вообще не должен уходить в API.

Добавь отдельную ручку `override suspend fun getAllTracks(): Result<List<Track>>`, где будет `page_size=100`

2022-12-08 08:01 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/interactor/TrackInteractor.kt
> +        trackRepository.getTrack(trackId)
не уверен насчет этого момента, в `TrackRepository`:
```kotlin
suspend fun getTrack(trackId: Long): Result<Track> =
    getTracks(listOf(trackId)).map { it.first() }
```

если `getTracks` вернет пустой список треков, то будет ли краш в `.map { it.first() }`
проверь этот момент пожалуйста

2022-12-08 08:25 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserActionDispatcher.kt
> +                    .filter { it.isBeta.not() }
Когда будем делать UI еще нужно будет не забыть проверить сортировку, возможно нужно как-то сортировать список треков.

2022-12-08 08:55 UTC, vladkash commented
@ivan-magda я даже думаю лучше тогда было не делать апрув сейчас, а просто сообщением это указать, мол  shared готов, двигаемся дальше

2022-12-08 09:36 UTC, vladkash commented
@ivan-magda походу придется еще доделать shared модуль, сейчас вник что рейтинг ведь у нас не в поле приходит, его тоже считать надо. Чтобы это все скрыть, скорее всего добавлю сюда viewData какую-нибудь, чтобы в треке сразу лежало готовое значение

2022-12-08 11:03 UTC, vladkash commented
@ivan-magda добавил, посмотришь?

2022-12-08 12:52 UTC, ivan-magda requested changes

2022-12-08 12:52 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserActionDispatcher.kt
> +                    .associateBy { it.vid.split('-').last().toLongOrNull() ?: 0 }
Для модели `Track` можно добавить поле с прогрессом:
```kotlin
@Serializable
data class Track(
    ...

    @Transient // Transient marks this property invisible for the whole serialization process
    val progress: TrackProgress? = null

    ...
)
```

`.associateBy { it.vid.split('-').last().toLongOrNull() ?: 0 }` какой-то сложный маппинг, можно проще:
```kotlin
val tracksIds = tracks.map { it.id }
if (tracksIds.isEmpty()) {
    return onNewMessage(Message.TracksLoaded.Success(emptyList()))
}

val tracksProgresses = progressesInteractor
    .getTracksProgresses(tracksIds = tracksIds)
    .getOrElse {
        onNewMessage(Message.TracksLoaded.Error)
        return
    }

val trackProgressById = tracksProgresses.associateBy { it.id }
val tracksWithProgresses = tracks.map { it.copy(progress = trackProgressById[it.progressId]) }

onNewMessage(Message.TracksLoaded.Success(tracksWithProgresses))
```

2022-12-08 12:52 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserActionDispatcher.kt
> +                    .getTracksProgresses(tracks.map { it.id })
Нужно проверить, что `tracks.size == tracksProgresses.size`. Не помню у бэкенда тоже 100 максимальный размер для `ids`.

Пока идет разработка фичи можно добавить проверку `require(tracks.size == tracksProgresses.size)`, потому ее удалим, т.к. она кидает ошибку `IllegalArgumentException`, если условие не выполнилось.

Сразу можно добавить логирование ошибки в Sentry, так мы в будущем можем понять, что у нас что-то сломалось:
```kotlin
sentryInteractor.captureErrorMessage("PlaceholderNewUser: tracks.size != tracksProgresses.size")
```

2022-12-08 12:52 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/view/mapper/PlaceholderNewUserViewDataMapper.kt
> +    }
В будущем нам следует сделать Formatter времени в shared, как есть в iOS проекте.

2022-12-08 12:52 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/view/model/PlaceholderNewUserTrack.kt
> +    val rating: String,
в конце последнего поля запятые не нужны `val rating: String,` -> `val rating: String`

2022-12-08 12:52 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/view/model/PlaceholderNewUserTrack.kt
> +data class PlaceholderNewUserTrack(
Если мы начали выносить ViewData в shared и мапить данные в ViewData, то здесь необходимо вынести не только список треков, но и все остальные данные необходимые для отображения UI экрана заглушки для новых пользователей:

```kotlin
class PlaceholderNewUserViewData(
    val title: String,
    ...
    val tracks: List<Track>
    ...
) {
    class Track(
        val id: Long,
        val imageSource: String,
        val title: String,
        val description: String,
        val timeToComplete: String,
        val rating: String
    )
}
```

2022-12-08 12:52 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/view/mapper/PlaceholderNewUserViewDataMapper.kt
> +    fun mapStateToTracks(state: PlaceholderNewUserFeature.State.Content): List<PlaceholderNewUserTrack> =
Refactor:
```
fun mapStateToViewData(state: PlaceholderNewUserFeature.State.Content): PlaceholderNewUserViewData
```

чтобы возращалась ViewData для отображения всего экрана

2022-12-08 12:52 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/model/TrackProgress.kt
> +    val vid: String,
можно удалить

2022-12-08 12:52 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserReducer.kt
>                  }
Можно убрать лишний уровень вложенности:
```kotlin
is Message.StartLearningButtonClicked -> {
    val targetTrack = (state as? State.Content)
        ?.tracks?.firstOrNull { it.id == message.trackId }

    if (targetTrack != null) {
        state to setOf(
            Action.SelectTrack(targetTrack),
            Action.LogAnalyticEvent(
                PlaceholderNewUserClickedHyperskillAnalyticEvent(
                    HyperskillAnalyticPart.TRACK_MODAL,
                    HyperskillAnalyticTarget.START_LEARNING,
                    targetTrack.id
                )
            ),
            Action.ViewAction.ShowTrackSelectionStatus.Loading
        )
    } else {
        null
    }
}
```

2022-12-08 12:52 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/injection/PlaceholderNewUserComponentImpl.kt
> +    override val placeHolderNewUserViewDataMapper: PlaceholderNewUserViewDataMapper
Add a new line between `placeholderNewUserFeature` and `placeHolderNewUserViewDataMapper`

2022-12-08 12:52 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserActionDispatcher.kt
> +                        return
Вообще можно писать в одну строку `return onNewMessage(Message.TrackSelected.Error)`, как мы это часто делаем на iOS, но мне без разницы, как привычно.

2022-12-09 08:46 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/view/mapper/PlaceholderNewUserViewDataMapper.kt
> +    }
Да, я записал себе, на следующем планинге подниму эту тему

2022-12-09 08:53 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/view/model/PlaceholderNewUserTrack.kt
> +data class PlaceholderNewUserTrack(
@ivan-magda мне больше нравится вариант с вынесением Track в nested class. Но я как не бьюсь не могу найти динамический заголовок на экране, который зависит от состояния. Кроме отображения треков и карточки трека у нас там два статический текста - "What is your learning goal?" и "Explore all tracks and find the right one by choosing a specific area of knowledge"

2022-12-09 08:58 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserActionDispatcher.kt
> +                        return
Мне так больше заходит, буду так писать

2022-12-09 09:01 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserActionDispatcher.kt
> +                    .associateBy { it.vid.split('-').last().toLongOrNull() ?: 0 }
Да, я уже второй раз наступаю на грабли неиспользования Transient. В следующий раз постараюсь учесть.

2022-12-09 09:49 UTC, ivan-magda reviewed
Все OK

2022-12-09 09:54 UTC, vladkash commented
@XanderZhu shared модуль можно использовать

2022-12-12 09:30 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserActionDispatcher.kt
> +                    .filter { it.isBeta.not() }
[Комментарий](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-437/iOS-Shared-Track-selection-for-new-users#focus=Comments-74-205028.0-0) от Егора

2022-12-12 11:16 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserActionDispatcher.kt
> +                    .filter { it.isBeta.not() }
```kotlin
tracks
    .sort((a, b) => a.progress?.rank - b.progress?.rank)
```

Тогда нам в модель `TrackProgress` нужно будет добавить поле `rank: Int = 0` и отспортировать потом по этому полю, прогрессы мы уже загружаем, поэтому все необходимые данные есть

2022-12-12 11:39 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserActionDispatcher.kt
> +                    .filter { it.isBeta.not() }
@ivan-magda добавил

2022-12-13 07:03 UTC, vladkash commented
@XanderZhu, кажется, что на андроиде используются ненужные уже строки placeholder_register_text и placeholder_instruction_text, ты бы не мог их выпилить?

2022-12-13 07:03 UTC, ivan-magda commented
я померджу этот PR

2022-12-13 07:04 UTC, ivan-magda commented
> @XanderZhu, кажется, что на андроиде используются ненужные уже строки placeholder_register_text и placeholder_instruction_text, ты бы не мог их выпилить?

да там неверный title и description, я исправлю, когда буду мерджить

2022-12-13 09:04 UTC, XanderZhu commented
@ivan-magda @vladkash 
Как вам идея делать `squash` коммитов ветки перед тем, как ее мерджить в develop?
Так можно будет убрать лишние детали в истории гита. В develop будет только один коммит со всеми изменениями. Не будет множества маленьких коммитов типа типа "fix ktlint" и прочего.

2022-12-13 09:21 UTC, ivan-magda commented
> 

Такое лучше обсуждать в Slack, на данный момент `squash` у нас запрещен в настройках репозитория.

2022-12-13 09:21 UTC, ivan-magda approved these changes

2022-12-13 09:22 UTC, merged