Features/altapps 47 updating ios login UI
hyperskill/mobile-app pull request #27
Opened 2022-04-06 09:42 UTC by vladkash

Task: [#ALTAPPS-47](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-47)

**Dependencies**
- !

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Наверстал что-то первоначальное, вынес логику кнопок соцсетей
- Как сделать тени на кнопках?
- Проблема с центрированием текста на кнопках, учитывается иконка, как можно ее заигнорировать?
- Пока не вынес все в Appearance, как устаканится макет вынесу
- Для того, чтобы оценивать адаптивную верстку просто в качестве девайса превью выбирать айпад?

2022-04-07 04:35 UTC, ivan-magda requested changes
@vladkash

> Как сделать тени на кнопках?

```swift
Button(
    action: {},
    label: {
        Text("Test")
            .background(Color.white)
    }
)
.cornerRadius(6)
.shadow(color: Color.black.opacity(0.1), radius: 4, x: 0, y: 1)
.padding(.horizontal, 20)
```

> Проблема с центрированием текста на кнопках, учитывается иконка, как можно ее заигнорировать?

Вот пример такой кнопки:
```swift
Button(
    action: {},
    label: {
        Text(getText())
            .font(.subheadline)
            .foregroundColor(.black)
            .frame(maxWidth: .infinity, minHeight: 48, alignment: .center)
            .overlay(
                Image(getIcon())
                    .frame(width: 24, height: 24)
                    .padding(.leading)
                ,
                alignment: .leading
            )
            .background(Color.white)
    }
)
.cornerRadius(6)
.shadow(color: Color.black.opacity(0.1), radius: 4, x: 0, y: 1)
.padding(.horizontal, 20)
```

> Для того, чтобы оценивать адаптивную верстку просто в качестве девайса превью выбирать айпад?

Да, в превью можно сразу указать несколько девайсов, чтобы было удобнее:
```swift
struct AuthView_Previews: PreviewProvider {
    static var previews: some View {
        Group {
            AuthAssembly().makeModule()
                .previewDevice(PreviewDevice(rawValue: "iPhone 13 Pro"))
            AuthAssembly().makeModule()
                .previewDevice(PreviewDevice(rawValue: "iPhone SE (3rd generation)"))
            AuthAssembly().makeModule()
                .previewDevice(PreviewDevice(rawValue: "iPad (9th generation)"))
        }
    }
}
```

Для реализации адаптивной верстки можно использовать [size classes](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/).
https://www.hackingwithswift.com/quick-start/swiftui/how-to-create-different-layouts-using-size-classes

2022-04-07 04:35 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Assets.xcassets/apple_icon.imageset/Contents.json
> +  "images" : [
Для картинок в Assets каталоге:
1. `apple_icon`
2. `close_icon`
3. `github_icon`
4. `google_icon`
5. `jb_icon`

`Scales` должен быть установлен в `Single Scale`. При добавлении нового изображения в pdf формате всегда необходимо дополнительно делать `Preserve Vector Data` и `Single Scale`.

2022-04-07 04:35 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Assets.xcassets/apple_icon.imageset/Contents.json
> +  "images" : [
Также я бы эти картинки назвал в формате `{NAME}-logo` (`apple-logo`, `github-logo`...).

2022-04-07 04:35 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthSocialButton.swift
> +    let provider: SocialProvider
Кнопке незачем знать о ViewModel, она просто отрисовывает данные, которые ей передали.

Нужно все передавать при инициализации:
```swift
init(text: String, imageName: String, action: @escaping () -> Void)
```

2022-04-07 04:35 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthView.swift
> +            Color(SharedResources.colors.shared.color_background.dynamicUIColor).ignoresSafeArea()
`ColorPalette.background`

2022-04-07 04:35 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthView.swift
> +                    Image("close_icon").frame(width: 16, height: 16).padding(.horizontal, 16)
Это должна быть кнопка

2022-04-07 04:35 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthView.swift
> +                    AuthSocialButton(viewModel: viewModel, provider: .apple)
Дублирование кода.

Лучше реализовать при помощи `ForEach`:
```swift
ForEach(self.viewModel.availableSocialAuthProviders, id: \.rawValue) { socialProvider in
    AuthSocialButton(provider: socialProvider)
}
```

2022-04-08 10:56 UTC, vladkash commented
@ivan-magda посмотри, пожалуйста, ориентируюсь на то, что осталось вынести что нужно в Appearance и добавить адаптивность

2022-04-08 11:52 UTC, ivan-magda requested changes

2022-04-08 11:52 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthSocialButton.swift
> +    let action: () -> Void
private

2022-04-08 11:52 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthSocialButton.swift
> +
лишний перенос строки

2022-04-08 11:52 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthSocialButton.swift
> +            },
`action: self.action,`

2022-04-08 11:52 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthSocialButton.swift
> +
Давай всегда использовать возможности SwiftUI Preview:
```swift
struct AuthSocialButton_Previews: PreviewProvider {
    static var previews: some View {
        // Init AuthSocialButton here
    }
}
```

2022-04-08 11:52 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthView.swift
> +fileprivate extension SocialProvider {
Я бы перенес это расширение ниже, перед `struct AuthView_Previews: PreviewProvider`

2022-04-08 11:52 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthView.swift
> +    var imageName: String {
перенос строки

2022-04-08 11:52 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthView.swift
> +                    ForEach(viewModel.availableSocialAuthProviders, id: \.rawValue) { provider in
👍

2022-04-08 11:52 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthViewModel.swift
> +    let availableSocialAuthProviders: [SocialProvider] = [.jetbrains, .google, .github, .apple]
```suggestion
    let availableSocialAuthProviders = SocialProvider.allCases
```

2022-04-10 06:45 UTC, vladkash commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthSocialButton.swift
> +    let action: () -> Void
мы так делаем, потому что извне в теории норм получить текст на кнопке, но не выполнить действие, которое должно быть по нажатию на нее?

2022-04-10 06:47 UTC, vladkash commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthSocialButton.swift
> +
да, когда не передаем viewModel в кнопку это легко стало сделать)

2022-04-10 06:49 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthSocialButton.swift
> +    let action: () -> Void
Да

2022-04-10 06:53 UTC, vladkash commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthView.swift
> +    var imageName: String {
не совсем понимаю, в чем тут проблема

2022-04-10 07:03 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/AuthView.swift
> +    var imageName: String {
> не совсем понимаю, в чем тут проблема

нет переноса строки:
```swift
fileprivate extension SocialProvider {
    var text: String {
        switch self {
        case .jetbrains:
            return "JetBrains Account"
        case .google:
            return "Google"
        case .github:
            return "GitHub"
        case .apple:
            return "Apple"
        }
    } // Здесь нет переноса строки
    var imageName: String {
        switch self {
        case .jetbrains:
            return "jetbrains_logo"
        case .google:
            return "google_logo"
        case .github:
            return "github_logo"
        case .apple:
            return "apple_logo"
        }
    }
}
```

⬇️

```swift
fileprivate extension SocialProvider {
    var text: String {
        switch self {
        case .jetbrains:
            return "JetBrains Account"
        case .google:
            return "Google"
        case .github:
            return "GitHub"
        case .apple:
            return "Apple"
        }
    }

    var imageName: String {
        switch self {
        case .jetbrains:
            return "jetbrains_logo"
        case .google:
            return "google_logo"
        case .github:
            return "github_logo"
        case .apple:
            return "apple_logo"
        }
    }
}
```

2022-04-10 07:44 UTC, vladkash commented
@ivan-magda написал код по ресайзу. Есть ощущение, что тексты и кнопки не такие большие, как на макете, но при этом, например, на макете размер как была высота кнопки 48, так и осталась. Как с этим быть?
P.S. в конце сделаю большой cleanup с использованием Appearance и ColorPallete

2022-04-11 03:43 UTC, ivan-magda approved these changes
Я внес правки в UI, можешь посмотреть на `AuthView`.

> написал код по ресайзу. Есть ощущение, что тексты и кнопки не такие большие, как на макете, но при этом, например, на макете размер как была высота кнопки 48, так и осталась. Как с этим быть?

Это визуальное искажение, размерности не изменяются.

> P.S. в конце сделаю большой cleanup с использованием Appearance и ColorPallete

Уже не нужно. Вообще насчет повсеместного использования `Appearance` меня уже начинают терзать сомнения, потому что в SwiftUI это не ложится, все равно потом к любой вьюшки извне можно применить `ViewModifier` и переопределить реализацию. Кажется использование `Appearance` в простых вьюшках (`AuthLogoView`, `AuthOutlineButton`, ...) излишне, а например в `AuthView` это ОК для группировки различных констант, которые оказывают влияние на UI.

2022-04-11 11:21 UTC, merged