ALTAPPS-424: Shared change endpoint config on demand & debug feature draft
hyperskill/mobile-app pull request #295
Opened 2022-12-29 04:04 UTC by ivan-magda

**YouTrack Issues**:
[#ALTAPPS-424](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-424)

**Checklist**

_Before Code Review:_

- [ ] Fields "Assignees, Labels, Milestone" are filled in the pull request;
- [ ] Sentry Performance Monitoring of screen loading is added for new screens;
- [ ] View analytics events are added for new screens;
- [ ] New analytics events are documented;
- [ ] All checks have been passed;
- [ ] Changes have been checked locally.

**Description**

2023-01-10 06:24 UTC, ivan-magda commented
@XanderZhu ping

2023-01-10 09:32 UTC, XanderZhu requested changes

2023-01-10 09:32 UTC, XanderZhu commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/sentry/domain/model/manager/SentryManagerImpl.kt
> +    lateinit var buildKonfig: BuildKonfig
Лучше не использовать lateinit перменные. В данном случае, можно поместить buildKonfig в конструктор класса, так как он нужне для его работы. Создание экземпляра SentryManagerImpl можно сжделать внутри AndroidAppComponent.

2023-01-11 09:08 UTC, XanderZhu approved these changes

2023-01-11 09:31 UTC, merged