ALTAPPS 53 IOS email login screen UI
hyperskill/mobile-app pull request #32
Opened 2022-04-13 10:50 UTC by vladkash

Task: [#ALTAPPS-53](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-53)

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Вьюшка с авторизацией через email AuthEmailView.swift, переход сделан через Binding
- Вынес форму в отдельный файл AuthEmailFormView.swift

2022-04-13 13:33 UTC, vladkash commented
Есть вопрос: я отрисовываю сообщение об ошибке на основании state-переменной. Как я могу в превью показать и экран с ошибкой, и без? То есть модифицировать state оттуда

2022-04-13 13:34 UTC, vladkash commented
Еще как-то надоело писать везде corner radius 8, его можно как-то по-умолчанию задать и везде потом использовать?

2022-04-13 14:10 UTC, ivan-magda commented
> Есть вопрос: я отрисовываю сообщение об ошибке на основании state-переменной. Как я могу в превью показать и экран с ошибкой, и без? То есть модифицировать state оттуда

```swift
struct AuthEmailFormView: View {
    ...
    @State private(set) var error = false
    ...
}

struct AuthEmailFormView_Previews: PreviewProvider {
    static var previews: some View {
        Group {
            AuthEmailFormView(error: false)

            AuthEmailFormView(error: true)
        }
    }
}
```

2022-04-13 15:54 UTC, ivan-magda requested changes
В целом ОК, нужно подмерджить develop и внести правки.
Еще сейчас есть проблема с клавиатурой - при фокусе на поле ввода её возможно скрыть только по нажатию на `Return key`, хочется чтобы её можно было скрыть по нажатию на экран и при скролле. Думаю такое должно легко нагуглится.

2022-04-13 15:54 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/Views/AuthEmailFormView.swift
> +            TextField(Strings.emailPlaceHolderText, text: $email)
Нужно отключить `capitalization`, `correction`, return key `Next` и по нажатию на него переводить фокус на поле ввода пароля.
В SwiftUI все это реализовать можно только с версии iOS 15.0 и выше, поэтому нужно писать враппер над `UITextFiled`, этим я займусь.

2022-04-13 15:54 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/Views/AuthEmailFormView.swift
> +                    .cornerRadius(8)
можно вынести в отдельную error view

2022-04-13 15:54 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/Views/AuthEmailFormView.swift
> +            ).cornerRadius(8)
После UI шага появился стиль кнопки `RoundedRectangleButtonStyle`, нужно develop ветку подмерджить и тогда такую кнопку можно будет реализовать просто:
```swift
Button(Strings.logInText, action: {})
	.buttonStyle(RoundedRectangleButtonStyle())
```

2022-04-13 15:54 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/Views/AuthEmailFormView.swift
> +        .cornerRadius(8)
По дизайну у формы еще должен быть `border`.

2022-04-13 15:54 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/Views/AuthEmailView.swift
> +                        .padding(.top)
После UI шага я эту кнопку удалил, заменил ее на стить `OutlineButtonStyle`, тоже будет доступно после мерджа develop ветки.

2022-04-13 15:59 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/Views/AuthEmailView.swift
> +}
Есть возможность создать immutable `Binding..constant(true)`.

```swift
struct AuthEmailView_Previews: PreviewProvider {
    static var previews: some View {
        AuthEmailView(presentingContinueWithEmail: .constant(true))
            .previewDevice(PreviewDevice(rawValue: "iPhone 13 Pro"))
    }
}
```

2022-04-14 09:23 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/Views/AuthEmailFormView.swift
> +            TextField(Strings.emailPlaceHolderText, text: $email)
@vladkash добавил и интегрировал `TextFieldWrapper`.

2022-04-14 14:08 UTC, vladkash commented
@ivan-magda помоги, пожалуйста, с рамкой для формы. Там получается нужна и рамка, и закругление, и задний фон. У меня то углы рамки режет, то закругления нет, то белый фон вылезает за пределы, разные методы пробовал

2022-04-15 03:28 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Auth/Views/AuthEmailFormView.swift
> +        .cornerRadius(8)
@vladkash смотри файл `Sources/Extensions/SwiftUI/View+Border.swift`

2022-04-15 04:33 UTC, ivan-magda approved these changes

2022-04-15 13:36 UTC, merged