ALTAPPS-680: Shared add progress into gamification toolbar
hyperskill/mobile-app pull request #430
Opened 2023-04-07 12:44 UTC by XanderZhu

**YouTrack Issues**:
[#ALTAPPS-680](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-680)

**Checklist**

_Before Code Review:_

- [ ] Fields "Assignees, Labels, Milestone" are filled in the pull request;
- [x] Sentry Performance Monitoring of screen loading is added for new screens;
- [ ] All checks have been passed;
- [ ] Changes have been checked locally.

**Description**
-

2023-04-10 11:28 UTC, ivan-magda requested changes
I think it's better not to merge this to `develop` because it adds new remote data loading without UI -> we don't want to call new remote data loading methods until the actual UI uses them.

2023-04-10 11:28 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/gamification_toolbar/presentation/GamificationToolbarActionDispatcher.kt
> +    private suspend fun fetchTrackWithProgressThoughtStudyPlan(forceLoadFromRemote: Boolean): Result<TrackWithProgress?> =
I suppose here you mean `Thought` -> `Through`

2023-04-10 11:28 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/gamification_toolbar/presentation/GamificationToolbarActionDispatcher.kt
> +    private suspend fun fetchTrackWithProgress(trackId: Long, forceLoadFromRemote: Boolean): Result<TrackWithProgress?> =
```suggestion
    private suspend fun fetchTrackWithProgress(
        trackId: Long,
        forceLoadFromRemote: Boolean
    ): Result<TrackWithProgress?> =
```

2023-04-10 11:28 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/gamification_toolbar/presentation/GamificationToolbarActionDispatcher.kt
> +                        ?: return@runCatching null
```suggestion
                    trackProgress = trackProgressDeferred.await().getOrThrow() ?: return@runCatching null
```

2023-04-10 11:28 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/gamification_toolbar/presentation/GamificationToolbarActionDispatcher.kt
> +                        ?: return@runCatching null
It's more readable when in one line

<img width="702" alt="Screenshot 2023-04-10 at 2 06 01 PM" src="https://user-images.githubusercontent.com/8586063/230890263-f6f5de0d-a86a-4f88-8c7e-2d24deec2828.png">

2023-04-10 11:28 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/gamification_toolbar/presentation/GamificationToolbarReducer.kt
> +
empty line

2023-04-10 11:28 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/gamification_toolbar/presentation/GamificationToolbarReducer.kt
> +
empty line

2023-04-10 11:34 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/Statistics/ProfileStatisticsItemView.swift
> +    @ViewBuilder private var image: some View {
This is maybe false positive, I'll look

<img width="1247" alt="Screenshot 2023-04-10 at 2 33 11 PM" src="https://user-images.githubusercontent.com/8586063/230893980-6c699d81-fde3-49c6-aa99-964cf4fe4c5d.png">

2023-04-10 16:28 UTC, XanderZhu commented
@ivan-magda 
> I think it's better not to merge this to develop because it adds new remote data loading without UI -> we don't want to call new remote data loading methods until the actual UI uses them.

Sure, we can create a Progresses feature branch to collect all the changes there.

2023-04-10 16:29 UTC, XanderZhu commented on shared/src/commonMain/kotlin/org/hyperskill/app/gamification_toolbar/presentation/GamificationToolbarReducer.kt
> +
Do you use custom linter settings?
`./gradlew ktlintCheck` doesn't show this issues

2023-04-10 17:12 UTC, XanderZhu commented
@ivan-magda 
Swift lint warning @ViewBuilder issues
https://github.com/hyperskill/mobile-app/actions/runs/4659392411/jobs/8246224372?pr=430

2023-04-11 11:10 UTC, ivan-magda approved these changes

2023-04-11 12:47 UTC, merged