ALTAPPS-851: Android project stage completion modals
hyperskill/mobile-app pull request #583
Opened 2023-07-13 12:43 UTC by vladkash

**YouTrack Issues**:
[#ALTAPPS-851](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-851)

**Checklist**

_Before Code Review:_

- [x] Fields "Assignees, Labels, Milestone" are filled in the pull request;
- [ ] All checks have been passed;
- [x  ] Changes have been checked locally.

**Description**
- Add modals for project and stage completion

2023-07-14 09:16 UTC, XanderZhu requested changes

2023-07-14 09:17 UTC, XanderZhu commented
@vladkash 
I forgot to tell you about large images.
It's possible to export large images from SVG to XML and use them. 
However, it has disadvantages in terms of performance: large SVG instructions are a few times slower than PNG rendering.
This is why for large images PNG format should be used. It's required to provide multiple file in different size for different screen resolutions. Usually, it's enough to support `mdpi`, `hdpi`, `xhdpi`, `xxhdpi` & `xxxhdpi`. [More about different pixel densities](https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp).

And another performance point.
PNG images occupy a lot of the device's disk space. To minify application size it's better to use WebP format instead of PNG. 

You can use [a special figma plugin](https://www.figma.com/community/plugin/1183975085577339184/Figma-Exporter) (it is available in dev mode) to export all required resolutions in WebP format (and then manually put exported files to the appropriate folder in the project).

Please, replace XML images with WebP for different screen resolutions.

2023-07-14 12:30 UTC, vladkash commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/stage_implementation/view/dialog/ProjectCompletedBottomSheet.kt
> +            projectCompletedGemsAmountForProjectCompletionTextView.text = "+${params.projectAward}"
I'm not sure how should I do that, add it to shared or use android local strings with `String.format`?

2023-07-18 08:14 UTC, XanderZhu commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/stage_implementation/view/dialog/ProjectCompletedBottomSheet.kt
> +            projectCompletedGemsAmountForProjectCompletionTextView.text = "+${params.projectAward}"
@vladkash 
You can add a template to the string resources (in android-app-module) and use it via context.getString(R.string.your_string_res, your_args).

2023-07-18 10:54 UTC, merged