ALTAPPS-891: Shared unlock study plan
hyperskill/mobile-app pull request #603
Opened 2023-07-28 11:41 UTC by vladkash

**YouTrack Issues**:
[#ALTAPPS-891](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-891)

**Checklist**

_Before Code Review:_

- [x] Fields "Assignees, Labels, Milestone" are filled in the pull request;
- [ ] All checks have been passed;
- [x] Changes have been checked locally.

**Description**
- Set all todo activities to next status

2023-07-28 12:38 UTC, XanderZhu approved these changes

2023-07-31 10:08 UTC, ivan-magda requested changes

2023-07-31 10:08 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/view/model/StudyPlanWidgetViewState.kt
> +            get() = state == SectionItemState.NEXT || state == SectionItemState.IDLE
The user should be able to click on any learning activity (like on the web), so let's delete `isClickable` property and all code that disables clicks on the platforms

2023-08-01 02:37 UTC, ivan-magda approved these changes

2023-08-01 07:28 UTC, merged