ALTAPPS-969: Shared show notification onboarding screen on user login
hyperskill/mobile-app pull request #664
Opened 2023-09-19 14:34 UTC by XanderZhu

**YouTrack Issues**:
[#ALTAPPS-969](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-969)

**Checklist**

_Before Code Review:_

- [x] Fields "Assignees, Labels, Milestone" are filled in the pull request;
- [x] View analytics events are added for new screens;
- [x] New analytics events are documented;
- [x] All checks have been passed;
- [x] Changes have been checked locally.

**Description**
- Implement NotificationsOnboardingFeature
- Implement navigation to NotificationsOnboardingFeature from the AppFeature
- Implement NotificationsOnboardingCompletion handling in the AppFeature

2023-09-20 10:44 UTC, ivan-magda requested changes
Business logic looks correct

2023-09-20 10:44 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification_onboarding/domain/analytics/NotificationsOnboardingClickedAllowNotificationsHyperskillAnalyticsEvent.kt
> +package org.hyperskill.app.notification_onboarding.domain.analytics
I suppose package name should be `notification_onboarding` -> `notifications_onboarding`

2023-09-20 10:44 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/main/presentation/AppFeature.kt
> +            val profile: Profile? = null
```suggestion
            internal val profile: Profile? = null
```

2023-09-20 10:44 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification_onboarding/domain/analytics/NotificationsOnboardingPermissionResultHyperskillAnalyticsEvent.kt
> +class NotificationsOnboardingPermissionResultHyperskillAnalyticsEvent(
We already have analytic events for the system prompt dialog:

1. https://github.com/hyperskill/mobile-app/blob/develop/shared/src/commonMain/kotlin/org/hyperskill/app/notification/local/domain/analytic/NotificationSystemNoticeShownHyperskillAnalyticEvent.kt
2. https://github.com/hyperskill/mobile-app/blob/develop/shared/src/commonMain/kotlin/org/hyperskill/app/notification/local/domain/analytic/NotificationSystemNoticeHiddenHyperskillAnalyticEvent.kt

2023-09-20 10:44 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification_onboarding/injection/NotificationsOnboardingComponent.kt
> +    val notificationOnboardingFeature: Feature<State, Message, Action>
`notificationsOnboardingFeature`

2023-09-20 10:44 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification_onboarding/presentation/NotificationsOnboardingActionDispatcher.kt
> +class NotificationsOnboardingActionDispatcher(
```suggestion
internal class NotificationsOnboardingActionDispatcher(
```

2023-09-20 10:44 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification_onboarding/presentation/NotificationsOnboardingReducer.kt
> +class NotificationsOnboardingReducer : StateReducer<State, Message, Action> {
```suggestion
internal class NotificationsOnboardingReducer : StateReducer<State, Message, Action> {
```

2023-09-20 10:44 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification_onboarding/presentation/NotificationsOnboardingFeature.kt
> +        data class LogAnalyticsEvent(val event: HyperskillAnalyticEvent) : Action
It's OK for such a small feature, but in the future it's better to separate Actions/Messages into public and internal like we do with previous features

2023-09-20 10:44 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/onboarding/cache/OnboardingCacheDataSourceImpl.kt
> +        settings.getBoolean(OnboardingCacheKeyValues.IS_NOTIFICATIONS_ONBOARDING_SHOWN, wasShown)
```suggestion
        settings.putBoolean(OnboardingCacheKeyValues.IS_NOTIFICATIONS_ONBOARDING_SHOWN, wasShown)
```

2023-09-20 10:44 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification_onboarding/injection/NotificationsOnboardingFeatureBuilder.kt
> +object NotificationsOnboardingFeatureBuilder {
```suggestion
internal object NotificationsOnboardingFeatureBuilder {
```

2023-09-20 10:44 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/notification_onboarding/injection/NotificationsOnboardingComponentImpl.kt
> +class NotificationsOnboardingComponentImpl(
Since we have `BaseAppGraph` with a common implementation -> we can make component implementation also internal

2023-09-20 13:29 UTC, ivan-magda approved these changes

2023-09-21 06:39 UTC, XanderZhu commented
@ivan-magda 
I suggest opening platform pull requests to this branch, because until the NotificationsOnboarding screen is implemented on the platform side, the user can finish its login flow.

2023-09-21 06:49 UTC, ivan-magda commented
> I suggest opening platform pull requests to this branch

@XanderZhu it's better to create a separate feature branch (`feature/notifications_onboarding`), where we will merge shared, Android and iOS PRs

2023-09-21 08:13 UTC, merged