ALTAPPS-176: Android Track View & Presentation
hyperskill/mobile-app pull request #85
Opened 2022-07-06 11:30 UTC by eqimd

Task: [#ALTAPPS-176](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-176)

**Reviewers**
- [ ] @rostikjoystick 

**Description**
- Add presentation layer for track
- Add injection in shared and android modules
- Add mandatory track progress with track info in feature
- Add track fragment
- Add Coil library
- Set track and progress info in fragment

2022-07-06 11:57 UTC, ivan-magda commented
@rostikjoystick @eqimd в качестве аватарки трека решили использовать `track. cover`? А там всегда только svg приходят, обрабатываете ли случай, когда к примеру в jpeg? Что будем делать с темной темой?

2022-07-06 12:04 UTC, eqimd commented
Все, что я смог натыкать (штук 10-15), были с SVG. Но заметил, что в некоторых треках (например id 35) приходит `null` в поле `cover`. Надо поправить и придумать, что с этим делать

2022-07-11 10:09 UTC, ivan-magda commented
@eqimd подмерджил сюда `develop`

2022-07-12 15:17 UTC, ivan-magda requested changes

2022-07-12 15:17 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/track/view/fragment/TrackFragment.kt
> +            trackAboutUsefulnessTextView.text = "${trackProgress.usefulness ?: "0"}"
Необходимо добавить следующую логику вычисления рейтинга, как на фронтенде:
```javascript
avgRating () {
  const avg = (this.progress.fun + this.progress.clarity +
    this.progress.usefulness) / 3

  return Math.round(avg * 10) / 10
}
```

На Kotlin будет так, предлагаю сразу это вынести в модель `TrackProgress`, также необходимо использовать `Double` при расчете.
```kotlin
val funMeasure = (trackProgress.funMeasure ?: 0).toDouble()
val clarity = (trackProgress.clarity ?: 0).toDouble()
val usefulness = (trackProgress.usefulness ?: 0).toDouble()

val avgRating = (funMeasure + clarity + usefulness) / 3
val roundedRating = (avgRating * 10).roundToInt() / 10.0
```

2022-07-12 15:17 UTC, ivan-magda commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/track/view/fragment/TrackFragment.kt
> +            trackAboutAllPerformTimeTextView.text = "${(track.secondsToComplete / 3600).roundToInt()} hours"
pluralize - 1 hour, 2 hours

2022-07-12 15:17 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/track/presentation/TrackActionDispatcher.kt
> +                val studyPlanResult = trackInteractor.getStudyPlanByTrackId(action.trackId)
Сетевые запросы выполняются последовательно `trackResult -> trackProgressResult -> studyPlanResult`, было бы намного лучше их сразу все выполнять параллельно.

2022-07-12 15:17 UTC, ivan-magda commented on shared/src/commonMain/resources/MR/base/strings.xml
> +    <string name="track_continue_in_web_text">&lt;u>Continue learning in web&lt;/u> \u2197</string>
Не забывай, что мы шарим строковые ресурсы между платформами и такое на iOS не работает, а если хочется использовать, то добавляй суффикс `android`.
Также на груминге мы решили, что стрелочку убираем -> `Continue learning in web`.

2022-07-12 15:26 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/track/presentation/TrackActionDispatcher.kt
> +                val studyPlanResult = trackInteractor.getStudyPlanByTrackId(action.trackId)
Если добавить здесь параллельность будет не просто, то оставь **TODO**, чтобы в будущем этот момент оптимизировали.

2022-07-12 16:31 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/repository/TrackRepository.kt
> +        getStudyPlans().map { it.first { plan -> plan.trackId == trackId } }
Спрашивал у бэка -- нету :(

2022-07-12 20:26 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/model/TrackProgress.kt
> +    val trackRating = (avgRating * 10).roundToInt() / 10.0
Обычно для этого используют computed property:
```kotlin
val averageRating: Double
    get() {
        val internalFunMeasure = (funMeasure ?: 0).toDouble()
        val internalClarity = (clarity ?: 0).toDouble()
        val internalUsefulness = (usefulness ?: 0).toDouble()
        val avgRating = (internalFunMeasure + internalClarity + internalUsefulness) / 3

        return (avgRating * 10).roundToInt() / 10.0
    }
```

2022-07-12 20:27 UTC, ivan-magda approved these changes

2022-07-13 06:51 UTC, merged