ALTAPPS-179: iOS profile view
hyperskill/mobile-app pull request #91
Opened 2022-07-08 21:08 UTC by ivan-magda

Task: [#ALTAPPS-179](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-179)

**Reviewers**
- [ ] @

**Description**
- Adds profile view

2022-07-09 18:03 UTC, ivan-magda commented
@eqimd 

Я добавил в shared модуль модель `HistoricalStreak` -> `Streak.history`. Далее нужно использовать `state` в `HistoricalStreak` для определения состояния стрика. `Streak.Kind` удалил и закоментил код в Android, где это использовалось. `Streak.Kind` используется для другого, возможные значения `steps|daily_steps`.

2022-07-09 19:13 UTC, eqimd requested changes

2022-07-09 19:13 UTC, eqimd commented on shared/src/commonMain/resources/MR/base/strings.xml
> +    <string name="profile_view_full_version_button_text_ios">View the full version of profile ↗</string>
В дизайне убрали стрелочку в конце (и такие символы лучше через юникод `\u...` прописывать)

2022-07-09 19:13 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileActionDispatcher.kt
> +                    )
Большая вложенность, мне кажется проще будет выглядеть, если сделать как в [диспатчере трека](https://github.com/hyperskill/mobile-app/blob/dd7d8245ae0818f62b52ae2b934af5754b791799/shared/src/commonMain/kotlin/org/hyperskill/app/track/presentation/TrackActionDispatcher.kt) в PR для андроид

2022-07-09 20:12 UTC, ivan-magda commented on shared/src/commonMain/resources/MR/base/strings.xml
> +    <string name="profile_view_full_version_button_text_ios">View the full version of profile ↗</string>
@eqimd 

Ага, спасибо, не заметил, что в дизайне изменилось.

> (и такие символы лучше через юникод \u... прописывать)

\u этот формат для Android. В Swift необязательно прописывать юникод символы и эмодзи, совершенно безопасно использовать их напрямую, а если хочется прописать, то нужно использовать формат `\u{CODE_GOES_HERE}`

2022-07-10 09:00 UTC, vladkash requested changes

2022-07-10 09:28 UTC, eqimd commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/ViewData/ProfileViewDataMapper.swift
> +        let role = profile.isStaff ? "JetBrains Academy Team" : "Learner"
Мне тоже кажется, что лучше этот маппер в shared добавить, он в Android-модуле тоже нужен

2022-07-10 11:14 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Assembly/ProfilePresentationDescription.swift
> +            return false
Такое сравнение не будет работать для enum's with associated types.

2022-07-10 11:17 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Assembly/ProfilePresentationDescription.swift
> +            return false
Вообще лучше использовать `switch` паттерн, потому что при изменении enum компилятор выдаст ошибку, что case не обработан.

2022-07-10 11:27 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/ViewData/ProfileViewDataMapper.swift
> +        let role = profile.isStaff ? "JetBrains Academy Team" : "Learner"
@vladkash 

> А это потом где-то выводится на экране?

Ну да, запусти приложение и открой вкладку профиля

> Может в shared модуль вынести?

Да, вынесу 👍

2022-07-10 11:43 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/ViewData/ProfileViewDataMapper.swift
> +        let role = profile.isStaff ? "JetBrains Academy Team" : "Learner"
@eqimd 

> Мне тоже кажется, что лучше этот маппер в shared добавить, он в Android-модуле тоже нужен

У нас `ui/view` платформо специфичные. Этот маппер просто преобразует domain модель из shared модуля в ожидаемый формат для ui слоя на iOS.

Частично компоненты форматирования выносить это ОК, а полностью мапперы для модуля выносить это плохая идея, потому что это вводит зависимость между платформами и неявные побочные эффекты при изменениях в маппере. Допустим если выносить этот маппер сейчас, то прийдется реализовывать `expect/actual` реализации для форматирования стран/языков. И еще то что генерирует KotlinNative довольно неудобно использовать в Swift.

Этот маппер останется в iOS.

2022-07-10 11:51 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/ProfileAvatarView.swift
> +                width: appearance.borderWidth,
Эта вьюшка в дальнейшем будет использоваться везде в приложении, где необходимо отображать аватары, поэтому необходимо предоставить максимальный простор для ее кастомизации.

Для ясности я лучше переименую эту вьюшку в `LazyAvatarView`.

2022-07-10 12:05 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/ProfileHeaderView.swift
> +                Spacer()
@vladkash 

> Раз у изображения фиксированные размеры

Да, у аватарки фиксированный размер, но не у самого контейнера. Высота контейнера динамически адаптируется под вложенный контент.

<img width="542" alt="Screen Shot 2022-07-10 at 4 03 49 PM" src="https://user-images.githubusercontent.com/8586063/178144101-46a5561c-d1b2-4ec3-8460-5fe642b62106.png">

> не лучше ли использовать spacing?

Нет не лучше и это может сломаться при незначительных изменениях, подумай почему и как.

> Превью этой вьюхи станет корректно отображаться

Я бы тебе не советовал всегда доверять превью, то что ты видешь на превью не всегда равно рантайму, я тебе советую запускать приложение, чтобы быть точно уверенным в реализации.

2022-07-10 13:31 UTC, vladkash approved these changes

2022-07-10 17:40 UTC, eqimd requested changes

2022-07-10 17:40 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileActionDispatcher.kt
> +                    .getOrNull()
Лучше завернуть в
```
.getOrElse {
    onNewMessage(Message.ProfileLoaded.Error(it.message ?: "")
    return
}
```
 тогда можно будет не проверять на `null` ниже и в описании ошибки использовать `it.message ?: ""`

2022-07-10 17:49 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileActionDispatcher.kt
> +                    .getOrNull()
Спасибо, пушнул

2022-07-10 17:55 UTC, eqimd approved these changes

2022-07-10 21:16 UTC, merged