ALTAPPS-178: Android Profile View
hyperskill/mobile-app pull request #92
Opened 2022-07-11 12:36 UTC by eqimd

Task: [#ALTAPPS-178](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-178)

**Reviewers**
- [ ] @ivan-magda

**Description**
- Make profile fragment
- Remade streak card with static fires
- Add library for languages and codes

2022-07-11 12:39 UTC, eqimd commented
* Добавил библиотеку для кодов стран и языков -- я не совсем разобрался, как это сделать встроенными средствами Android-а, если вообще можно
* Удалил RecyclerView для огоньков в карточке стрика -- я не смог разобраться, как сделать так, чтобы элементы внутри recycler-а автоматически распределялись по всей ширине, поэтому просто захардкодил LinearLayout с днями внутри. По сути стало даже проще, т.к. теперь не нужен адаптер, но расширяемость стала похуже -- если надо будет, чтоб дней было не 5, а больше, то придется добавлять их руками внутрь LinearLayout-а и в цикл, с recycler-ом этого по сути можно было бы избежать

2022-07-12 13:03 UTC, ivan-magda requested changes
1. Присутствуют ошибки в отображении состояния стриков по дням.
2. Также необходимо добавить `pluralize` для текста текущего стрика - `1 day`, `2 days`

Android:
<img width="551" alt="Screen Shot 2022-07-12 at 5 00 54 PM" src="https://user-images.githubusercontent.com/8586063/178495992-78e7dffd-802d-4c11-bed7-3bf93e10bd1d.png">

Web:
<img width="770" alt="Screen Shot 2022-07-12 at 3 19 15 PM" src="https://user-images.githubusercontent.com/8586063/178495814-50cd3643-ceae-4031-a6bf-b1d5f8913004.png">

iOS:
<img width="480" alt="Screen Shot 2022-07-12 at 3 19 26 PM" src="https://user-images.githubusercontent.com/8586063/178495836-49b19c9d-b268-417c-b6de-2cb0ce2ec0d0.png">

2022-07-12 13:42 UTC, eqimd commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt
> +        viewBinding.profileNameTextView.text = profile.fullname
Да, он грузит и jpeg и png (в частности, у меня аватарка в png)

2022-07-12 13:46 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/profile/view/social_redirect/SocialNetworksRedirect.kt
> +    GITHUB("http://github.com/")
смысла по сути нет, будет авторедирект, но ок

2022-07-12 16:08 UTC, eqimd commented on androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt
> +        }
Мне кажется, что не стоит -- сильная привязка к платформенным локалям, по сути просто получится интерфейс, который особо не должен расширяться и при этом дополнительно будет много кода, когда в отдельных модулях это реализуется одной строчкой, я думаю если бы это было как-то больше связано с shared-модулем (какой-то общей библиотекой, например), тогда можно было бы

2022-07-12 16:24 UTC, eqimd commented
Забыл добавить pluralize -- позже добавлю

2022-07-12 19:43 UTC, ivan-magda approved these changes

2022-07-13 06:40 UTC, merged