ALTAPPS-185: iOS homescreen view+presentation
hyperskill/mobile-app pull request #94
Opened 2022-07-13 16:08 UTC by vladkash

Task: [#ALTAPPS-185](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-185)

**Dependencies**
- !

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Added homescreen presentation logic
- Connected presentation logic with iOS view

2022-07-13 21:21 UTC, ivan-magda requested changes

2022-07-13 21:21 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt
> +                    }
Можно вынести в отдельную функцию:
```kotlin
private suspend fun getProblemOfDayState(dailyStepId: Long?): Result<HomeFeature.ProblemOfDayState> =
    if (dailyStepId == null) {
        Result.success(HomeFeature.ProblemOfDayState.Empty)
    } else {
        stepInteractor
            .getStep(dailyStepId)
            .map { step ->
                if (step.isCompleted) {
                    HomeFeature.ProblemOfDayState.Solved(step)
                } else {
                    HomeFeature.ProblemOfDayState.NeedToSolve(step)
                }
            }
    }
```

и потом вызвать:
```kotlin
val problemOfDayState = getProblemOfDayState(currentProfile.dailyStep)
    .getOrElse {
        onNewMessage(Message.HomeFailure)
        return
    }
```

2022-07-13 21:21 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt
> +                onNewMessage(Message.HomeSuccess(streak, problemOfDayState))
Можно упростить:
```kotlin
val message = streakInteractor
    .getStreaks(currentProfile.id)
    .map { Message.HomeSuccess(it.firstOrNull(), problemOfDayState) }
    .getOrElse { Message.HomeFailure }

onNewMessage(message)
```

2022-07-13 21:21 UTC, ivan-magda commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeFeature.kt
> +            Message
На одной строке
```kotlin
data class HomeSuccess(val streak: Streak?, val problemOfDayState: ProblemOfDayState) : Message
```

2022-07-14 08:08 UTC, vladkash commented
@ivan-magda а ты точно не хочешь ничего сказать по функции, которая считает время до 00:00 следующего дня по Нью-Йорку? Она находится в HomeView, над ней TODO. Мне просто показалось, что скорее всего я написал ее ужасно, но чет какое-то апи неприятное для работы с датой-временем

2022-07-14 08:10 UTC, ivan-magda commented
> @ivan-magda а ты точно не хочешь ничего сказать по функции, которая считает время до 00:00 следующего дня по Нью-Йорку? Она находится в HomeView, над ней TODO. Мне просто показалось, что скорее всего я написал ее ужасно, но чет какое-то апи неприятное для работы с датой-временем

@vladkash я пока что смотрел только `shared`, iOS ещё буду проверять.

2022-07-14 08:49 UTC, eqimd reviewed
Не хватает `PlatformHomeComponent` и чтоб все Home-компоненты в Android-модуле были. Добавь `PlatformHomeComponent`, я потом добавлю код, нужный для Android-модуля

2022-07-14 09:21 UTC, vladkash commented
@eqimd добавил, посмотри, пожалуйста, что все правильно

2022-07-14 10:03 UTC, eqimd approved these changes

2022-07-19 07:42 UTC, ivan-magda requested changes
Для манипуляций с датами будем использовать [SwiftDate](https://github.com/malcommac/SwiftDate), необходимо добавить зависимость.

Для расчета даты, когда задача дня обновляется в 00:00 по NY можно использовать https://github.com/malcommac/SwiftDate#7-switch-between-timezoneslocale-and-calendars. 

Также необходимо добавить счетчик до этого момента, который каждую секунду будет обновлять время до 00:00 по NY. Это можно вынести в `ProblemOfDayTimeRemainingView`, которая в качестве параметра будет принимать дату, когда задача дня обновляется, а счетчик до этого момента можно реализовать с помощью [Timer](https://developer.apple.com/documentation/foundation/timer) API.

Также по аналогии с другими модулями для карточки задачи дня нужно добавить `Assembly/ViewData/ViewDataMapper`.

2022-07-25 12:45 UTC, eqimd requested changes
Касательно комментариев по диспатчеру -- лучше еще дождаться ревью от @rostikjoystick

2022-07-25 12:45 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt
> +            while (true) {
Мне не очень нравится здесь бесконечный цикл. Мне кажется, что цикл нужно прерывать, когда истекает время `nextProblemIn` -- потому что после этого что-то считать бессмысленно.
Так же возможно стоит не вычитать из `nextProblemIn` секунды, а просто пересчиытвать `calculateNextProblemIn()`, но это скорее всего будет дольше
Этот `flow` лучше вынести в отдельную переменную и не создавать его в блоке `init {...}`, а создавать и запускать на `Action.FetchHomeScreenData`

2022-07-26 07:25 UTC, vladkash commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt
> +            while (true) {
Мне нравится идея прерывать flow и вынести его в FetchHomeScreenData. Если просто пересчитывать `calculateNextProblemIn()`, то секунды всегда будут положительными и не удастся на view слое понять, что пора показывать кнопку перезагрузки, просто с 1 минуты сменится на 23 часа 59 минут

2022-07-27 10:54 UTC, vladkash commented
@rostikjoystick @eqimd  я перенес таймер в действие

2022-07-27 12:56 UTC, eqimd approved these changes

2022-07-27 12:56 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt
> +                    val delay = 1.toDuration(DurationUnit.MINUTES)
Лучше в константу в `companion object`

2022-07-27 12:56 UTC, eqimd commented on shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt
> +                    while (true) {
Я бы переделал цикл вместе с `flow` как-нибудь так:
```kotlin
flow {
    var nextProblemIn = calculateNextProblemIn()
    emit(nextProblemIn)

    while (nextProblemIn > 0) {
        nextProblemIn -= delay.inWholeSeconds
        emit(nextProblemIn)
        
        delay(DELAY_ONE_MINUTE)
    }
}
```

2022-07-27 15:34 UTC, ivan-magda approved these changes

2022-07-27 15:59 UTC, rostikjoystick commented
Поддерживаю комментарии @eqimd 
Еще было бы неплохо посылать сообщение, когда таймер истек, чтобы потом в Reducer'е обработать состояние, когда нужно показать кнопку Refresh

2022-07-28 07:42 UTC, rostikjoystick approved these changes

2022-07-28 08:15 UTC, merged