ALTAPPS-192: iOS quiz skeletons realization
hyperskill/mobile-app pull request #96
Opened 2022-07-16 10:18 UTC by vladkash

Task: [#ALTAPPS-192](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-192)

**Dependencies**
- !

**Reviewers**
- [ ] @ivan-magda 

**Description**
- StepQuizSkeletonView позволяет конфигурировать размеры и количество скелетонов для различных видов задач

2022-07-16 10:20 UTC, vladkash commented
@ivan-magda Кажется, что нельзя регулировать размер скелетонов в зависимости от типов ответов, ведь на этапе загрузки мы их еще не знаем. То есть вряд ли выйдет сделать скелетоны, как здесь 
<img width="479" alt="image" src="https://user-images.githubusercontent.com/30647936/179350845-4fd87a5d-c765-4c77-abed-86034da30430.png">
Кроме того, я не нашел дизайнов скелетонов для, например, задач на код, поэтому оставил стандартные

2022-07-18 09:12 UTC, ivan-magda requested changes
Будет лучше, если UI каждого из скелетонов будет реализован в соответствующем модуле соответствующей задачи, так будет проще и понятнее реализовывать кастомные layout'ы и вносить изменения в будущем.
Нужно `StepQuizSkeletonView` заменить на фабрику скелетонов:
```swift
import SwiftUI

enum StepQuizSkeletonViewFactory {
    @ViewBuilder
    static func makeSkeleton(for quizType: StepQuizChildQuizType) -> some View {
        switch quizType {
        case .choice:
            StepQuizChoiceSkeletonView()
        case .matching:
            StepQuizMatchingSkeletonView()
        case .sorting:
            StepQuizSortingSkeletonView()
        case .table:
            StepQuizTableSkeletonView()
        case .string, .number, .math:
            StepQuizStringSkeletonView()
        case .unsupported(let blockName):
            fatalError("StepQuizSkeletonViewFactory :: did receive unsupported quizType = \(blockName)")
        }
    }
}
```

UI skeletons:
- [choice](https://www.figma.com/file/P693bQAvnQgLcX46Kv5aQt/%F0%9F%94%B4-Step%3A-Theory-%26-Practice?node-id=932%3A21929)
- [matching](https://www.figma.com/file/P693bQAvnQgLcX46Kv5aQt/%F0%9F%94%B4-Step%3A-Theory-%26-Practice?node-id=1397%3A47321)
- [sorting](https://www.figma.com/file/P693bQAvnQgLcX46Kv5aQt/%F0%9F%94%B4-Step%3A-Theory-%26-Practice?node-id=1397%3A47513)
- [table](https://www.figma.com/file/P693bQAvnQgLcX46Kv5aQt/%F0%9F%94%B4-Step%3A-Theory-%26-Practice?node-id=1397%3A47766)
- [string](https://www.figma.com/file/P693bQAvnQgLcX46Kv5aQt/%F0%9F%94%B4-Step%3A-Theory-%26-Practice?node-id=933%3A28757)

Если для какой-то задачи нет макета скелетона, то можно посмотреть на макет задачи и примерно понять/перенести UI задачи в скелетон.

2022-07-18 12:28 UTC, vladkash commented
@ivan-magda а ты не мог бы рассказать потенциальные кейсы изменений, вносить которые будет легче в твоем варианте? Просто кроме того, что вьюшка, ответственная за конкретную задачу будет лежать в папке задачи мне не видно плюсов, а накидывать столько вьюх для скелетонов кажется избыточным. Хочется делать с точным осознанием, зачем оно с точки зрения выгод разработки)

2022-07-18 13:09 UTC, ivan-magda commented
> @ivan-magda а ты не мог бы рассказать потенциальные кейсы изменений, вносить которые будет легче в твоем варианте? Просто кроме того, что вьюшка, ответственная за конкретную задачу будет лежать в папке задачи мне не видно плюсов, а накидывать столько вьюх для скелетонов кажется избыточным. Хочется делать с точным осознанием, зачем оно с точки зрения выгод разработки)

Для примера можешь посмотреть какие тебе необходимо будет внести изменения в текущую реализацию, чтобы реализовать скелетоны для matching задачи. В итоге у тебя базовый скелетон (прямоугольник) будет обрастать ифами в виде computed properties. Также при добавлении новых задач или внесения изменений к старым нет гарантий, что они не привнесут побочный эффект.

> а ты не мог бы рассказать потенциальные кейсы изменений, вносить которые будет легче в твоем варианте?

1. Добавление новой задачи - просто создал новый файл в соответствующем модуле соответствующей задачи, обработал в switch case.
2. Обновление дизайна задачи - изменил файл в соответствующем модуле соответствующей задачи.

В обоих примерах точно можно быть уверенным, что ты ни как не повлияешь на реализацию других скелетонов задач.

Еще будет хуже если допустим пройдет какое-то время и ты забудешь контекст реализации StepQuizSkeletonView, тогда прийдется вспоминать какая computed property за что отвечает и какое изменение необходимо внести, чтобы сделать то что ты хочешь.

> Просто кроме того, что вьюшка, ответственная за конкретную задачу будет лежать в папке задачи мне не видно плюсов, а накидывать столько вьюх для скелетонов кажется избыточным.

Не вижу здесь проблем, выше написал, почему на мой взгляд это лучше, а также лучше, когда все компоненты имеющие отношение к модулю находятся в рамках этого модуля.

2022-07-19 11:54 UTC, vladkash commented
@ivan-magda кажется я понял, о чем ты. Просто мне при реализации казалось, что каждый скелетон характеризуется просто высотами прямоугольников, больше там ничего не будет меняться. То есть в случае matching задачи у скелетонов такие же отступы появляются и они не на всю ширину будут? Увидь я это в дизайне, конечно сразу бы начал делать разделение. Ну или в описании задачи было бы здорово указать было, что если нет дизайна, это означает, что скелетон должен плюс минус элементы повторять. Из-за недостатка опыта мне это было неочевидно. Спасибо большое за детальный ответ!

2022-07-19 14:42 UTC, ivan-magda commented
@vladkash 

> То есть в случае matching задачи у скелетонов такие же отступы появляются и они не на всю ширину будут?

Да, не на всю ширину, с отступами.

> Увидь я это в дизайне, конечно сразу бы начал делать разделение. Ну или в описании задачи было бы здорово указать было, что если нет дизайна, это означает, что скелетон должен плюс минус элементы повторять.

В итоге хорошо, что мы поняли друг друга 👍 Обычно в дизайне скелетоны отсутствуют и следует ориентироваться на то, что скелетон должен повторять UI элемент.

2022-07-20 10:44 UTC, merged