ALTAPPS-199: iOS local notifications widget UI
hyperskill/mobile-app pull request #99
Opened 2022-07-21 09:56 UTC by vladkash

Task: [#ALTAPPS-199](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-199)

**Dependencies**
- !

**Reviewers**
- [ ] @ivan-magda 

**Description**
- Добавлен виджет выбора времени напоминаний
- Нужен совет, как лучше сделать внешний вид пикера (серый цвет + chevron), делать свой picker style? Пытался сделать через List/Form, но не заводится (просто не выводится компонент), видимо из-за того, что используется NavigationView на верхнем уровне

2022-07-26 14:30 UTC, ivan-magda requested changes
@vladkash 

> Нужен совет, как лучше сделать внешний вид пикера (серый цвет + chevron), делать свой picker style? Пытался сделать через List/Form, но не заводится (просто не выводится компонент), видимо из-за того, что используется NavigationView на верхнем уровне

Делать свой делать свой picker style кажется избыточно, лучше использовать готовые системные компоненты. Вообще в iOS паттерн серый цвет + chevron должен использоваться в тех случаях, когда по нажатию будет показываться детальный экран для выбора элемента, а у нас это не предполагается.

В данном случае у нас `.pickerStyle(.menu)` и мне очень нравится его внешний вид и поведение. Предлагаю только добавить `.accentColor(Color(ColorPalette.primary))`, чтобы использовался брендированный цвет для выбранного элемента:
```swift
Picker("", selection: $selectedInterval) {
    ForEach(intervals.reversed(), id: \.self) { interval in
        Text(formatInterval(interval: interval)).tag(interval)
    }
}
.accentColor(Color(ColorPalette.primary))
```

Потом на груминге можно будет показать команде дизайна, как мы сделали и почему.

2022-07-26 14:30 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/Reminders/ProfileRemindersView.swift
> +struct ProfileRemindersView: View {
Давай так назовем `ProfileDailyStudyRemindersView`

2022-07-26 14:30 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/Reminders/ProfileRemindersView.swift
> +    @State private var activated = true
Пусть на данный момент по умолчанию будет деактивировано `isActivated = false`

2022-07-26 14:30 UTC, ivan-magda commented on iosHyperskillApp/iosHyperskillApp/Sources/Views/HourIntervalPicker.swift
> +                }
Так на заметку, как работает `ForEach`:

`ForEach` автоматически устанавливает tag в соответсвии с id (`tag = id`), поэтому устанавливать вручную опционально и в нашем случае это еще безопасно, потому что типы `selectedInterval.Type == ID.Type`.

- https://sarunw.com/posts/how-to-use-swiftui-picker/#foreach-automatically-assigns-a-tag
- https://sarunw.com/posts/create-list-of-views-in-swiftui-using-foreach/

2022-07-26 14:31 UTC, ivan-magda commented on shared/src/commonMain/resources/MR/base/strings.xml
> +    <!--  -->
можно удалить

2022-07-27 07:43 UTC, vladkash commented
@ivan-magda да, мне тоже зашел такой вид picker-а

2022-07-27 08:27 UTC, ivan-magda approved these changes

2022-07-27 12:12 UTC, merged